// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressPb.proto

package com.amazaar.Protobuff;

public final class AddressPbOuterClass {
  private AddressPbOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.amazaar.Protobuff.CityEnum}
   */
  public enum CityEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN_CITY = 0;</code>
     */
    UNKNOWN_CITY(0),
    /**
     * <code>LUCKNOW = 1;</code>
     */
    LUCKNOW(1),
    /**
     * <code>SITAPUR = 2;</code>
     */
    SITAPUR(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN_CITY = 0;</code>
     */
    public static final int UNKNOWN_CITY_VALUE = 0;
    /**
     * <code>LUCKNOW = 1;</code>
     */
    public static final int LUCKNOW_VALUE = 1;
    /**
     * <code>SITAPUR = 2;</code>
     */
    public static final int SITAPUR_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CityEnum valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static CityEnum forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN_CITY;
        case 1: return LUCKNOW;
        case 2: return SITAPUR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CityEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CityEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CityEnum>() {
            public CityEnum findValueByNumber(int number) {
              return CityEnum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.amazaar.Protobuff.AddressPbOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final CityEnum[] VALUES = values();

    public static CityEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private CityEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.amazaar.Protobuff.CityEnum)
  }

  /**
   * Protobuf enum {@code com.amazaar.Protobuff.StateEnum}
   */
  public enum StateEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN_STATE = 0;</code>
     */
    UNKNOWN_STATE(0),
    /**
     * <code>UTTAR_PRADESH = 1;</code>
     */
    UTTAR_PRADESH(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN_STATE = 0;</code>
     */
    public static final int UNKNOWN_STATE_VALUE = 0;
    /**
     * <code>UTTAR_PRADESH = 1;</code>
     */
    public static final int UTTAR_PRADESH_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static StateEnum valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static StateEnum forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN_STATE;
        case 1: return UTTAR_PRADESH;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<StateEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        StateEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<StateEnum>() {
            public StateEnum findValueByNumber(int number) {
              return StateEnum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.amazaar.Protobuff.AddressPbOuterClass.getDescriptor().getEnumTypes().get(1);
    }

    private static final StateEnum[] VALUES = values();

    public static StateEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private StateEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.amazaar.Protobuff.StateEnum)
  }

  public interface AddressPbOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.amazaar.Protobuff.AddressPb)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string homeNo = 1;</code>
     * @return The homeNo.
     */
    java.lang.String getHomeNo();
    /**
     * <code>string homeNo = 1;</code>
     * @return The bytes for homeNo.
     */
    com.google.protobuf.ByteString
        getHomeNoBytes();

    /**
     * <code>string street = 2;</code>
     * @return The street.
     */
    java.lang.String getStreet();
    /**
     * <code>string street = 2;</code>
     * @return The bytes for street.
     */
    com.google.protobuf.ByteString
        getStreetBytes();

    /**
     * <code>string landMark = 3;</code>
     * @return The landMark.
     */
    java.lang.String getLandMark();
    /**
     * <code>string landMark = 3;</code>
     * @return The bytes for landMark.
     */
    com.google.protobuf.ByteString
        getLandMarkBytes();

    /**
     * <code>.com.amazaar.Protobuff.CityEnum city = 4;</code>
     * @return The enum numeric value on the wire for city.
     */
    int getCityValue();
    /**
     * <code>.com.amazaar.Protobuff.CityEnum city = 4;</code>
     * @return The city.
     */
    com.amazaar.Protobuff.AddressPbOuterClass.CityEnum getCity();

    /**
     * <code>.com.amazaar.Protobuff.StateEnum state = 5;</code>
     * @return The enum numeric value on the wire for state.
     */
    int getStateValue();
    /**
     * <code>.com.amazaar.Protobuff.StateEnum state = 5;</code>
     * @return The state.
     */
    com.amazaar.Protobuff.AddressPbOuterClass.StateEnum getState();

    /**
     * <code>int32 pincode = 6;</code>
     * @return The pincode.
     */
    int getPincode();
  }
  /**
   * Protobuf type {@code com.amazaar.Protobuff.AddressPb}
   */
  public static final class AddressPb extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.amazaar.Protobuff.AddressPb)
      AddressPbOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AddressPb.newBuilder() to construct.
    private AddressPb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AddressPb() {
      homeNo_ = "";
      street_ = "";
      landMark_ = "";
      city_ = 0;
      state_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AddressPb();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AddressPb(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              homeNo_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              street_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              landMark_ = s;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              city_ = rawValue;
              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              state_ = rawValue;
              break;
            }
            case 48: {

              pincode_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.amazaar.Protobuff.AddressPbOuterClass.internal_static_com_amazaar_Protobuff_AddressPb_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.amazaar.Protobuff.AddressPbOuterClass.internal_static_com_amazaar_Protobuff_AddressPb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.amazaar.Protobuff.AddressPbOuterClass.AddressPb.class, com.amazaar.Protobuff.AddressPbOuterClass.AddressPb.Builder.class);
    }

    public static final int HOMENO_FIELD_NUMBER = 1;
    private volatile java.lang.Object homeNo_;
    /**
     * <code>string homeNo = 1;</code>
     * @return The homeNo.
     */
    @java.lang.Override
    public java.lang.String getHomeNo() {
      java.lang.Object ref = homeNo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        homeNo_ = s;
        return s;
      }
    }
    /**
     * <code>string homeNo = 1;</code>
     * @return The bytes for homeNo.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHomeNoBytes() {
      java.lang.Object ref = homeNo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        homeNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STREET_FIELD_NUMBER = 2;
    private volatile java.lang.Object street_;
    /**
     * <code>string street = 2;</code>
     * @return The street.
     */
    @java.lang.Override
    public java.lang.String getStreet() {
      java.lang.Object ref = street_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        street_ = s;
        return s;
      }
    }
    /**
     * <code>string street = 2;</code>
     * @return The bytes for street.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStreetBytes() {
      java.lang.Object ref = street_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        street_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LANDMARK_FIELD_NUMBER = 3;
    private volatile java.lang.Object landMark_;
    /**
     * <code>string landMark = 3;</code>
     * @return The landMark.
     */
    @java.lang.Override
    public java.lang.String getLandMark() {
      java.lang.Object ref = landMark_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        landMark_ = s;
        return s;
      }
    }
    /**
     * <code>string landMark = 3;</code>
     * @return The bytes for landMark.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLandMarkBytes() {
      java.lang.Object ref = landMark_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        landMark_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CITY_FIELD_NUMBER = 4;
    private int city_;
    /**
     * <code>.com.amazaar.Protobuff.CityEnum city = 4;</code>
     * @return The enum numeric value on the wire for city.
     */
    @java.lang.Override public int getCityValue() {
      return city_;
    }
    /**
     * <code>.com.amazaar.Protobuff.CityEnum city = 4;</code>
     * @return The city.
     */
    @java.lang.Override public com.amazaar.Protobuff.AddressPbOuterClass.CityEnum getCity() {
      @SuppressWarnings("deprecation")
      com.amazaar.Protobuff.AddressPbOuterClass.CityEnum result = com.amazaar.Protobuff.AddressPbOuterClass.CityEnum.valueOf(city_);
      return result == null ? com.amazaar.Protobuff.AddressPbOuterClass.CityEnum.UNRECOGNIZED : result;
    }

    public static final int STATE_FIELD_NUMBER = 5;
    private int state_;
    /**
     * <code>.com.amazaar.Protobuff.StateEnum state = 5;</code>
     * @return The enum numeric value on the wire for state.
     */
    @java.lang.Override public int getStateValue() {
      return state_;
    }
    /**
     * <code>.com.amazaar.Protobuff.StateEnum state = 5;</code>
     * @return The state.
     */
    @java.lang.Override public com.amazaar.Protobuff.AddressPbOuterClass.StateEnum getState() {
      @SuppressWarnings("deprecation")
      com.amazaar.Protobuff.AddressPbOuterClass.StateEnum result = com.amazaar.Protobuff.AddressPbOuterClass.StateEnum.valueOf(state_);
      return result == null ? com.amazaar.Protobuff.AddressPbOuterClass.StateEnum.UNRECOGNIZED : result;
    }

    public static final int PINCODE_FIELD_NUMBER = 6;
    private int pincode_;
    /**
     * <code>int32 pincode = 6;</code>
     * @return The pincode.
     */
    @java.lang.Override
    public int getPincode() {
      return pincode_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getHomeNoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, homeNo_);
      }
      if (!getStreetBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, street_);
      }
      if (!getLandMarkBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, landMark_);
      }
      if (city_ != com.amazaar.Protobuff.AddressPbOuterClass.CityEnum.UNKNOWN_CITY.getNumber()) {
        output.writeEnum(4, city_);
      }
      if (state_ != com.amazaar.Protobuff.AddressPbOuterClass.StateEnum.UNKNOWN_STATE.getNumber()) {
        output.writeEnum(5, state_);
      }
      if (pincode_ != 0) {
        output.writeInt32(6, pincode_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getHomeNoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, homeNo_);
      }
      if (!getStreetBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, street_);
      }
      if (!getLandMarkBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, landMark_);
      }
      if (city_ != com.amazaar.Protobuff.AddressPbOuterClass.CityEnum.UNKNOWN_CITY.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, city_);
      }
      if (state_ != com.amazaar.Protobuff.AddressPbOuterClass.StateEnum.UNKNOWN_STATE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, state_);
      }
      if (pincode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, pincode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.amazaar.Protobuff.AddressPbOuterClass.AddressPb)) {
        return super.equals(obj);
      }
      com.amazaar.Protobuff.AddressPbOuterClass.AddressPb other = (com.amazaar.Protobuff.AddressPbOuterClass.AddressPb) obj;

      if (!getHomeNo()
          .equals(other.getHomeNo())) return false;
      if (!getStreet()
          .equals(other.getStreet())) return false;
      if (!getLandMark()
          .equals(other.getLandMark())) return false;
      if (city_ != other.city_) return false;
      if (state_ != other.state_) return false;
      if (getPincode()
          != other.getPincode()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + HOMENO_FIELD_NUMBER;
      hash = (53 * hash) + getHomeNo().hashCode();
      hash = (37 * hash) + STREET_FIELD_NUMBER;
      hash = (53 * hash) + getStreet().hashCode();
      hash = (37 * hash) + LANDMARK_FIELD_NUMBER;
      hash = (53 * hash) + getLandMark().hashCode();
      hash = (37 * hash) + CITY_FIELD_NUMBER;
      hash = (53 * hash) + city_;
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + state_;
      hash = (37 * hash) + PINCODE_FIELD_NUMBER;
      hash = (53 * hash) + getPincode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.amazaar.Protobuff.AddressPbOuterClass.AddressPb parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.amazaar.Protobuff.AddressPbOuterClass.AddressPb parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.amazaar.Protobuff.AddressPbOuterClass.AddressPb parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.amazaar.Protobuff.AddressPbOuterClass.AddressPb parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.amazaar.Protobuff.AddressPbOuterClass.AddressPb parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.amazaar.Protobuff.AddressPbOuterClass.AddressPb parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.amazaar.Protobuff.AddressPbOuterClass.AddressPb parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.amazaar.Protobuff.AddressPbOuterClass.AddressPb parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.amazaar.Protobuff.AddressPbOuterClass.AddressPb parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.amazaar.Protobuff.AddressPbOuterClass.AddressPb parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.amazaar.Protobuff.AddressPbOuterClass.AddressPb parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.amazaar.Protobuff.AddressPbOuterClass.AddressPb parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.amazaar.Protobuff.AddressPbOuterClass.AddressPb prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.amazaar.Protobuff.AddressPb}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.amazaar.Protobuff.AddressPb)
        com.amazaar.Protobuff.AddressPbOuterClass.AddressPbOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.amazaar.Protobuff.AddressPbOuterClass.internal_static_com_amazaar_Protobuff_AddressPb_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.amazaar.Protobuff.AddressPbOuterClass.internal_static_com_amazaar_Protobuff_AddressPb_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.amazaar.Protobuff.AddressPbOuterClass.AddressPb.class, com.amazaar.Protobuff.AddressPbOuterClass.AddressPb.Builder.class);
      }

      // Construct using com.amazaar.Protobuff.AddressPbOuterClass.AddressPb.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        homeNo_ = "";

        street_ = "";

        landMark_ = "";

        city_ = 0;

        state_ = 0;

        pincode_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.amazaar.Protobuff.AddressPbOuterClass.internal_static_com_amazaar_Protobuff_AddressPb_descriptor;
      }

      @java.lang.Override
      public com.amazaar.Protobuff.AddressPbOuterClass.AddressPb getDefaultInstanceForType() {
        return com.amazaar.Protobuff.AddressPbOuterClass.AddressPb.getDefaultInstance();
      }

      @java.lang.Override
      public com.amazaar.Protobuff.AddressPbOuterClass.AddressPb build() {
        com.amazaar.Protobuff.AddressPbOuterClass.AddressPb result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.amazaar.Protobuff.AddressPbOuterClass.AddressPb buildPartial() {
        com.amazaar.Protobuff.AddressPbOuterClass.AddressPb result = new com.amazaar.Protobuff.AddressPbOuterClass.AddressPb(this);
        result.homeNo_ = homeNo_;
        result.street_ = street_;
        result.landMark_ = landMark_;
        result.city_ = city_;
        result.state_ = state_;
        result.pincode_ = pincode_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.amazaar.Protobuff.AddressPbOuterClass.AddressPb) {
          return mergeFrom((com.amazaar.Protobuff.AddressPbOuterClass.AddressPb)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.amazaar.Protobuff.AddressPbOuterClass.AddressPb other) {
        if (other == com.amazaar.Protobuff.AddressPbOuterClass.AddressPb.getDefaultInstance()) return this;
        if (!other.getHomeNo().isEmpty()) {
          homeNo_ = other.homeNo_;
          onChanged();
        }
        if (!other.getStreet().isEmpty()) {
          street_ = other.street_;
          onChanged();
        }
        if (!other.getLandMark().isEmpty()) {
          landMark_ = other.landMark_;
          onChanged();
        }
        if (other.city_ != 0) {
          setCityValue(other.getCityValue());
        }
        if (other.state_ != 0) {
          setStateValue(other.getStateValue());
        }
        if (other.getPincode() != 0) {
          setPincode(other.getPincode());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.amazaar.Protobuff.AddressPbOuterClass.AddressPb parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.amazaar.Protobuff.AddressPbOuterClass.AddressPb) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object homeNo_ = "";
      /**
       * <code>string homeNo = 1;</code>
       * @return The homeNo.
       */
      public java.lang.String getHomeNo() {
        java.lang.Object ref = homeNo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          homeNo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string homeNo = 1;</code>
       * @return The bytes for homeNo.
       */
      public com.google.protobuf.ByteString
          getHomeNoBytes() {
        java.lang.Object ref = homeNo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          homeNo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string homeNo = 1;</code>
       * @param value The homeNo to set.
       * @return This builder for chaining.
       */
      public Builder setHomeNo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        homeNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string homeNo = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearHomeNo() {
        
        homeNo_ = getDefaultInstance().getHomeNo();
        onChanged();
        return this;
      }
      /**
       * <code>string homeNo = 1;</code>
       * @param value The bytes for homeNo to set.
       * @return This builder for chaining.
       */
      public Builder setHomeNoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        homeNo_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object street_ = "";
      /**
       * <code>string street = 2;</code>
       * @return The street.
       */
      public java.lang.String getStreet() {
        java.lang.Object ref = street_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          street_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string street = 2;</code>
       * @return The bytes for street.
       */
      public com.google.protobuf.ByteString
          getStreetBytes() {
        java.lang.Object ref = street_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          street_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string street = 2;</code>
       * @param value The street to set.
       * @return This builder for chaining.
       */
      public Builder setStreet(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        street_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string street = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStreet() {
        
        street_ = getDefaultInstance().getStreet();
        onChanged();
        return this;
      }
      /**
       * <code>string street = 2;</code>
       * @param value The bytes for street to set.
       * @return This builder for chaining.
       */
      public Builder setStreetBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        street_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object landMark_ = "";
      /**
       * <code>string landMark = 3;</code>
       * @return The landMark.
       */
      public java.lang.String getLandMark() {
        java.lang.Object ref = landMark_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          landMark_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string landMark = 3;</code>
       * @return The bytes for landMark.
       */
      public com.google.protobuf.ByteString
          getLandMarkBytes() {
        java.lang.Object ref = landMark_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          landMark_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string landMark = 3;</code>
       * @param value The landMark to set.
       * @return This builder for chaining.
       */
      public Builder setLandMark(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        landMark_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string landMark = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLandMark() {
        
        landMark_ = getDefaultInstance().getLandMark();
        onChanged();
        return this;
      }
      /**
       * <code>string landMark = 3;</code>
       * @param value The bytes for landMark to set.
       * @return This builder for chaining.
       */
      public Builder setLandMarkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        landMark_ = value;
        onChanged();
        return this;
      }

      private int city_ = 0;
      /**
       * <code>.com.amazaar.Protobuff.CityEnum city = 4;</code>
       * @return The enum numeric value on the wire for city.
       */
      @java.lang.Override public int getCityValue() {
        return city_;
      }
      /**
       * <code>.com.amazaar.Protobuff.CityEnum city = 4;</code>
       * @param value The enum numeric value on the wire for city to set.
       * @return This builder for chaining.
       */
      public Builder setCityValue(int value) {
        
        city_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.amazaar.Protobuff.CityEnum city = 4;</code>
       * @return The city.
       */
      @java.lang.Override
      public com.amazaar.Protobuff.AddressPbOuterClass.CityEnum getCity() {
        @SuppressWarnings("deprecation")
        com.amazaar.Protobuff.AddressPbOuterClass.CityEnum result = com.amazaar.Protobuff.AddressPbOuterClass.CityEnum.valueOf(city_);
        return result == null ? com.amazaar.Protobuff.AddressPbOuterClass.CityEnum.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.amazaar.Protobuff.CityEnum city = 4;</code>
       * @param value The city to set.
       * @return This builder for chaining.
       */
      public Builder setCity(com.amazaar.Protobuff.AddressPbOuterClass.CityEnum value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        city_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.amazaar.Protobuff.CityEnum city = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCity() {
        
        city_ = 0;
        onChanged();
        return this;
      }

      private int state_ = 0;
      /**
       * <code>.com.amazaar.Protobuff.StateEnum state = 5;</code>
       * @return The enum numeric value on the wire for state.
       */
      @java.lang.Override public int getStateValue() {
        return state_;
      }
      /**
       * <code>.com.amazaar.Protobuff.StateEnum state = 5;</code>
       * @param value The enum numeric value on the wire for state to set.
       * @return This builder for chaining.
       */
      public Builder setStateValue(int value) {
        
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.amazaar.Protobuff.StateEnum state = 5;</code>
       * @return The state.
       */
      @java.lang.Override
      public com.amazaar.Protobuff.AddressPbOuterClass.StateEnum getState() {
        @SuppressWarnings("deprecation")
        com.amazaar.Protobuff.AddressPbOuterClass.StateEnum result = com.amazaar.Protobuff.AddressPbOuterClass.StateEnum.valueOf(state_);
        return result == null ? com.amazaar.Protobuff.AddressPbOuterClass.StateEnum.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.amazaar.Protobuff.StateEnum state = 5;</code>
       * @param value The state to set.
       * @return This builder for chaining.
       */
      public Builder setState(com.amazaar.Protobuff.AddressPbOuterClass.StateEnum value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        state_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.amazaar.Protobuff.StateEnum state = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearState() {
        
        state_ = 0;
        onChanged();
        return this;
      }

      private int pincode_ ;
      /**
       * <code>int32 pincode = 6;</code>
       * @return The pincode.
       */
      @java.lang.Override
      public int getPincode() {
        return pincode_;
      }
      /**
       * <code>int32 pincode = 6;</code>
       * @param value The pincode to set.
       * @return This builder for chaining.
       */
      public Builder setPincode(int value) {
        
        pincode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 pincode = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearPincode() {
        
        pincode_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.amazaar.Protobuff.AddressPb)
    }

    // @@protoc_insertion_point(class_scope:com.amazaar.Protobuff.AddressPb)
    private static final com.amazaar.Protobuff.AddressPbOuterClass.AddressPb DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.amazaar.Protobuff.AddressPbOuterClass.AddressPb();
    }

    public static com.amazaar.Protobuff.AddressPbOuterClass.AddressPb getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AddressPb>
        PARSER = new com.google.protobuf.AbstractParser<AddressPb>() {
      @java.lang.Override
      public AddressPb parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AddressPb(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AddressPb> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AddressPb> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.amazaar.Protobuff.AddressPbOuterClass.AddressPb getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_amazaar_Protobuff_AddressPb_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_amazaar_Protobuff_AddressPb_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017addressPb.proto\022\025com.amazaar.Protobuff" +
      "\"\256\001\n\tAddressPb\022\016\n\006homeNo\030\001 \001(\t\022\016\n\006street" +
      "\030\002 \001(\t\022\020\n\010landMark\030\003 \001(\t\022-\n\004city\030\004 \001(\0162\037" +
      ".com.amazaar.Protobuff.CityEnum\022/\n\005state" +
      "\030\005 \001(\0162 .com.amazaar.Protobuff.StateEnum" +
      "\022\017\n\007pincode\030\006 \001(\005*6\n\010CityEnum\022\020\n\014UNKNOWN" +
      "_CITY\020\000\022\013\n\007LUCKNOW\020\001\022\013\n\007SITAPUR\020\002*1\n\tSta" +
      "teEnum\022\021\n\rUNKNOWN_STATE\020\000\022\021\n\rUTTAR_PRADE" +
      "SH\020\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_amazaar_Protobuff_AddressPb_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_amazaar_Protobuff_AddressPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_amazaar_Protobuff_AddressPb_descriptor,
        new java.lang.String[] { "HomeNo", "Street", "LandMark", "City", "State", "Pincode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
