// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: confirmOrderDeliveryPb.proto

package com.amazaar.Protobuff;

public final class ConfirmOrderDeliveryPbOuterClass {
  private ConfirmOrderDeliveryPbOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ConfirmOrderDeliveryPbOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.amazaar.Protobuff.ConfirmOrderDeliveryPb)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string customerId = 1;</code>
     * @return The customerId.
     */
    java.lang.String getCustomerId();
    /**
     * <code>string customerId = 1;</code>
     * @return The bytes for customerId.
     */
    com.google.protobuf.ByteString
        getCustomerIdBytes();

    /**
     * <code>string parentOrderId = 2;</code>
     * @return The parentOrderId.
     */
    java.lang.String getParentOrderId();
    /**
     * <code>string parentOrderId = 2;</code>
     * @return The bytes for parentOrderId.
     */
    com.google.protobuf.ByteString
        getParentOrderIdBytes();

    /**
     * <code>repeated .com.amazaar.Protobuff.BuyPb orderList = 3;</code>
     */
    java.util.List<com.amazaar.Protobuff.BuyPbOuterClass.BuyPb> 
        getOrderListList();
    /**
     * <code>repeated .com.amazaar.Protobuff.BuyPb orderList = 3;</code>
     */
    com.amazaar.Protobuff.BuyPbOuterClass.BuyPb getOrderList(int index);
    /**
     * <code>repeated .com.amazaar.Protobuff.BuyPb orderList = 3;</code>
     */
    int getOrderListCount();
    /**
     * <code>repeated .com.amazaar.Protobuff.BuyPb orderList = 3;</code>
     */
    java.util.List<? extends com.amazaar.Protobuff.BuyPbOuterClass.BuyPbOrBuilder> 
        getOrderListOrBuilderList();
    /**
     * <code>repeated .com.amazaar.Protobuff.BuyPb orderList = 3;</code>
     */
    com.amazaar.Protobuff.BuyPbOuterClass.BuyPbOrBuilder getOrderListOrBuilder(
        int index);

    /**
     * <code>.com.amazaar.Protobuff.TimePb time = 4;</code>
     * @return Whether the time field is set.
     */
    boolean hasTime();
    /**
     * <code>.com.amazaar.Protobuff.TimePb time = 4;</code>
     * @return The time.
     */
    com.amazaar.Protobuff.TimePbOuterClass.TimePb getTime();
    /**
     * <code>.com.amazaar.Protobuff.TimePb time = 4;</code>
     */
    com.amazaar.Protobuff.TimePbOuterClass.TimePbOrBuilder getTimeOrBuilder();

    /**
     * <code>.com.amazaar.Protobuff.IsOrderedPlacedEnum status = 5;</code>
     * @return The enum numeric value on the wire for status.
     */
    int getStatusValue();
    /**
     * <code>.com.amazaar.Protobuff.IsOrderedPlacedEnum status = 5;</code>
     * @return The status.
     */
    com.amazaar.Protobuff.BuyPbOuterClass.IsOrderedPlacedEnum getStatus();

    /**
     * <code>repeated string data = 6;</code>
     * @return A list containing the data.
     */
    java.util.List<java.lang.String>
        getDataList();
    /**
     * <code>repeated string data = 6;</code>
     * @return The count of data.
     */
    int getDataCount();
    /**
     * <code>repeated string data = 6;</code>
     * @param index The index of the element to return.
     * @return The data at the given index.
     */
    java.lang.String getData(int index);
    /**
     * <code>repeated string data = 6;</code>
     * @param index The index of the value to return.
     * @return The bytes of the data at the given index.
     */
    com.google.protobuf.ByteString
        getDataBytes(int index);
  }
  /**
   * Protobuf type {@code com.amazaar.Protobuff.ConfirmOrderDeliveryPb}
   */
  public static final class ConfirmOrderDeliveryPb extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.amazaar.Protobuff.ConfirmOrderDeliveryPb)
      ConfirmOrderDeliveryPbOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ConfirmOrderDeliveryPb.newBuilder() to construct.
    private ConfirmOrderDeliveryPb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConfirmOrderDeliveryPb() {
      customerId_ = "";
      parentOrderId_ = "";
      orderList_ = java.util.Collections.emptyList();
      status_ = 0;
      data_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ConfirmOrderDeliveryPb();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ConfirmOrderDeliveryPb(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              customerId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              parentOrderId_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                orderList_ = new java.util.ArrayList<com.amazaar.Protobuff.BuyPbOuterClass.BuyPb>();
                mutable_bitField0_ |= 0x00000001;
              }
              orderList_.add(
                  input.readMessage(com.amazaar.Protobuff.BuyPbOuterClass.BuyPb.parser(), extensionRegistry));
              break;
            }
            case 34: {
              com.amazaar.Protobuff.TimePbOuterClass.TimePb.Builder subBuilder = null;
              if (time_ != null) {
                subBuilder = time_.toBuilder();
              }
              time_ = input.readMessage(com.amazaar.Protobuff.TimePbOuterClass.TimePb.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(time_);
                time_ = subBuilder.buildPartial();
              }

              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                data_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              data_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          orderList_ = java.util.Collections.unmodifiableList(orderList_);
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          data_ = data_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.amazaar.Protobuff.ConfirmOrderDeliveryPbOuterClass.internal_static_com_amazaar_Protobuff_ConfirmOrderDeliveryPb_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.amazaar.Protobuff.ConfirmOrderDeliveryPbOuterClass.internal_static_com_amazaar_Protobuff_ConfirmOrderDeliveryPb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.amazaar.Protobuff.ConfirmOrderDeliveryPbOuterClass.ConfirmOrderDeliveryPb.class, com.amazaar.Protobuff.ConfirmOrderDeliveryPbOuterClass.ConfirmOrderDeliveryPb.Builder.class);
    }

    public static final int CUSTOMERID_FIELD_NUMBER = 1;
    private volatile java.lang.Object customerId_;
    /**
     * <code>string customerId = 1;</code>
     * @return The customerId.
     */
    @java.lang.Override
    public java.lang.String getCustomerId() {
      java.lang.Object ref = customerId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        customerId_ = s;
        return s;
      }
    }
    /**
     * <code>string customerId = 1;</code>
     * @return The bytes for customerId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCustomerIdBytes() {
      java.lang.Object ref = customerId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        customerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARENTORDERID_FIELD_NUMBER = 2;
    private volatile java.lang.Object parentOrderId_;
    /**
     * <code>string parentOrderId = 2;</code>
     * @return The parentOrderId.
     */
    @java.lang.Override
    public java.lang.String getParentOrderId() {
      java.lang.Object ref = parentOrderId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        parentOrderId_ = s;
        return s;
      }
    }
    /**
     * <code>string parentOrderId = 2;</code>
     * @return The bytes for parentOrderId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getParentOrderIdBytes() {
      java.lang.Object ref = parentOrderId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        parentOrderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORDERLIST_FIELD_NUMBER = 3;
    private java.util.List<com.amazaar.Protobuff.BuyPbOuterClass.BuyPb> orderList_;
    /**
     * <code>repeated .com.amazaar.Protobuff.BuyPb orderList = 3;</code>
     */
    @java.lang.Override
    public java.util.List<com.amazaar.Protobuff.BuyPbOuterClass.BuyPb> getOrderListList() {
      return orderList_;
    }
    /**
     * <code>repeated .com.amazaar.Protobuff.BuyPb orderList = 3;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.amazaar.Protobuff.BuyPbOuterClass.BuyPbOrBuilder> 
        getOrderListOrBuilderList() {
      return orderList_;
    }
    /**
     * <code>repeated .com.amazaar.Protobuff.BuyPb orderList = 3;</code>
     */
    @java.lang.Override
    public int getOrderListCount() {
      return orderList_.size();
    }
    /**
     * <code>repeated .com.amazaar.Protobuff.BuyPb orderList = 3;</code>
     */
    @java.lang.Override
    public com.amazaar.Protobuff.BuyPbOuterClass.BuyPb getOrderList(int index) {
      return orderList_.get(index);
    }
    /**
     * <code>repeated .com.amazaar.Protobuff.BuyPb orderList = 3;</code>
     */
    @java.lang.Override
    public com.amazaar.Protobuff.BuyPbOuterClass.BuyPbOrBuilder getOrderListOrBuilder(
        int index) {
      return orderList_.get(index);
    }

    public static final int TIME_FIELD_NUMBER = 4;
    private com.amazaar.Protobuff.TimePbOuterClass.TimePb time_;
    /**
     * <code>.com.amazaar.Protobuff.TimePb time = 4;</code>
     * @return Whether the time field is set.
     */
    @java.lang.Override
    public boolean hasTime() {
      return time_ != null;
    }
    /**
     * <code>.com.amazaar.Protobuff.TimePb time = 4;</code>
     * @return The time.
     */
    @java.lang.Override
    public com.amazaar.Protobuff.TimePbOuterClass.TimePb getTime() {
      return time_ == null ? com.amazaar.Protobuff.TimePbOuterClass.TimePb.getDefaultInstance() : time_;
    }
    /**
     * <code>.com.amazaar.Protobuff.TimePb time = 4;</code>
     */
    @java.lang.Override
    public com.amazaar.Protobuff.TimePbOuterClass.TimePbOrBuilder getTimeOrBuilder() {
      return getTime();
    }

    public static final int STATUS_FIELD_NUMBER = 5;
    private int status_;
    /**
     * <code>.com.amazaar.Protobuff.IsOrderedPlacedEnum status = 5;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.com.amazaar.Protobuff.IsOrderedPlacedEnum status = 5;</code>
     * @return The status.
     */
    @java.lang.Override public com.amazaar.Protobuff.BuyPbOuterClass.IsOrderedPlacedEnum getStatus() {
      @SuppressWarnings("deprecation")
      com.amazaar.Protobuff.BuyPbOuterClass.IsOrderedPlacedEnum result = com.amazaar.Protobuff.BuyPbOuterClass.IsOrderedPlacedEnum.valueOf(status_);
      return result == null ? com.amazaar.Protobuff.BuyPbOuterClass.IsOrderedPlacedEnum.UNRECOGNIZED : result;
    }

    public static final int DATA_FIELD_NUMBER = 6;
    private com.google.protobuf.LazyStringList data_;
    /**
     * <code>repeated string data = 6;</code>
     * @return A list containing the data.
     */
    public com.google.protobuf.ProtocolStringList
        getDataList() {
      return data_;
    }
    /**
     * <code>repeated string data = 6;</code>
     * @return The count of data.
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated string data = 6;</code>
     * @param index The index of the element to return.
     * @return The data at the given index.
     */
    public java.lang.String getData(int index) {
      return data_.get(index);
    }
    /**
     * <code>repeated string data = 6;</code>
     * @param index The index of the value to return.
     * @return The bytes of the data at the given index.
     */
    public com.google.protobuf.ByteString
        getDataBytes(int index) {
      return data_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getCustomerIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, customerId_);
      }
      if (!getParentOrderIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, parentOrderId_);
      }
      for (int i = 0; i < orderList_.size(); i++) {
        output.writeMessage(3, orderList_.get(i));
      }
      if (time_ != null) {
        output.writeMessage(4, getTime());
      }
      if (status_ != com.amazaar.Protobuff.BuyPbOuterClass.IsOrderedPlacedEnum.UNKNOWN_ORDER.getNumber()) {
        output.writeEnum(5, status_);
      }
      for (int i = 0; i < data_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, data_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getCustomerIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, customerId_);
      }
      if (!getParentOrderIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, parentOrderId_);
      }
      for (int i = 0; i < orderList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, orderList_.get(i));
      }
      if (time_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getTime());
      }
      if (status_ != com.amazaar.Protobuff.BuyPbOuterClass.IsOrderedPlacedEnum.UNKNOWN_ORDER.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, status_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < data_.size(); i++) {
          dataSize += computeStringSizeNoTag(data_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getDataList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.amazaar.Protobuff.ConfirmOrderDeliveryPbOuterClass.ConfirmOrderDeliveryPb)) {
        return super.equals(obj);
      }
      com.amazaar.Protobuff.ConfirmOrderDeliveryPbOuterClass.ConfirmOrderDeliveryPb other = (com.amazaar.Protobuff.ConfirmOrderDeliveryPbOuterClass.ConfirmOrderDeliveryPb) obj;

      if (!getCustomerId()
          .equals(other.getCustomerId())) return false;
      if (!getParentOrderId()
          .equals(other.getParentOrderId())) return false;
      if (!getOrderListList()
          .equals(other.getOrderListList())) return false;
      if (hasTime() != other.hasTime()) return false;
      if (hasTime()) {
        if (!getTime()
            .equals(other.getTime())) return false;
      }
      if (status_ != other.status_) return false;
      if (!getDataList()
          .equals(other.getDataList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CUSTOMERID_FIELD_NUMBER;
      hash = (53 * hash) + getCustomerId().hashCode();
      hash = (37 * hash) + PARENTORDERID_FIELD_NUMBER;
      hash = (53 * hash) + getParentOrderId().hashCode();
      if (getOrderListCount() > 0) {
        hash = (37 * hash) + ORDERLIST_FIELD_NUMBER;
        hash = (53 * hash) + getOrderListList().hashCode();
      }
      if (hasTime()) {
        hash = (37 * hash) + TIME_FIELD_NUMBER;
        hash = (53 * hash) + getTime().hashCode();
      }
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      if (getDataCount() > 0) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getDataList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.amazaar.Protobuff.ConfirmOrderDeliveryPbOuterClass.ConfirmOrderDeliveryPb parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.amazaar.Protobuff.ConfirmOrderDeliveryPbOuterClass.ConfirmOrderDeliveryPb parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.amazaar.Protobuff.ConfirmOrderDeliveryPbOuterClass.ConfirmOrderDeliveryPb parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.amazaar.Protobuff.ConfirmOrderDeliveryPbOuterClass.ConfirmOrderDeliveryPb parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.amazaar.Protobuff.ConfirmOrderDeliveryPbOuterClass.ConfirmOrderDeliveryPb parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.amazaar.Protobuff.ConfirmOrderDeliveryPbOuterClass.ConfirmOrderDeliveryPb parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.amazaar.Protobuff.ConfirmOrderDeliveryPbOuterClass.ConfirmOrderDeliveryPb parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.amazaar.Protobuff.ConfirmOrderDeliveryPbOuterClass.ConfirmOrderDeliveryPb parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.amazaar.Protobuff.ConfirmOrderDeliveryPbOuterClass.ConfirmOrderDeliveryPb parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.amazaar.Protobuff.ConfirmOrderDeliveryPbOuterClass.ConfirmOrderDeliveryPb parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.amazaar.Protobuff.ConfirmOrderDeliveryPbOuterClass.ConfirmOrderDeliveryPb parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.amazaar.Protobuff.ConfirmOrderDeliveryPbOuterClass.ConfirmOrderDeliveryPb parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.amazaar.Protobuff.ConfirmOrderDeliveryPbOuterClass.ConfirmOrderDeliveryPb prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.amazaar.Protobuff.ConfirmOrderDeliveryPb}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.amazaar.Protobuff.ConfirmOrderDeliveryPb)
        com.amazaar.Protobuff.ConfirmOrderDeliveryPbOuterClass.ConfirmOrderDeliveryPbOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.amazaar.Protobuff.ConfirmOrderDeliveryPbOuterClass.internal_static_com_amazaar_Protobuff_ConfirmOrderDeliveryPb_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.amazaar.Protobuff.ConfirmOrderDeliveryPbOuterClass.internal_static_com_amazaar_Protobuff_ConfirmOrderDeliveryPb_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.amazaar.Protobuff.ConfirmOrderDeliveryPbOuterClass.ConfirmOrderDeliveryPb.class, com.amazaar.Protobuff.ConfirmOrderDeliveryPbOuterClass.ConfirmOrderDeliveryPb.Builder.class);
      }

      // Construct using com.amazaar.Protobuff.ConfirmOrderDeliveryPbOuterClass.ConfirmOrderDeliveryPb.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getOrderListFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        customerId_ = "";

        parentOrderId_ = "";

        if (orderListBuilder_ == null) {
          orderList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          orderListBuilder_.clear();
        }
        if (timeBuilder_ == null) {
          time_ = null;
        } else {
          time_ = null;
          timeBuilder_ = null;
        }
        status_ = 0;

        data_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.amazaar.Protobuff.ConfirmOrderDeliveryPbOuterClass.internal_static_com_amazaar_Protobuff_ConfirmOrderDeliveryPb_descriptor;
      }

      @java.lang.Override
      public com.amazaar.Protobuff.ConfirmOrderDeliveryPbOuterClass.ConfirmOrderDeliveryPb getDefaultInstanceForType() {
        return com.amazaar.Protobuff.ConfirmOrderDeliveryPbOuterClass.ConfirmOrderDeliveryPb.getDefaultInstance();
      }

      @java.lang.Override
      public com.amazaar.Protobuff.ConfirmOrderDeliveryPbOuterClass.ConfirmOrderDeliveryPb build() {
        com.amazaar.Protobuff.ConfirmOrderDeliveryPbOuterClass.ConfirmOrderDeliveryPb result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.amazaar.Protobuff.ConfirmOrderDeliveryPbOuterClass.ConfirmOrderDeliveryPb buildPartial() {
        com.amazaar.Protobuff.ConfirmOrderDeliveryPbOuterClass.ConfirmOrderDeliveryPb result = new com.amazaar.Protobuff.ConfirmOrderDeliveryPbOuterClass.ConfirmOrderDeliveryPb(this);
        int from_bitField0_ = bitField0_;
        result.customerId_ = customerId_;
        result.parentOrderId_ = parentOrderId_;
        if (orderListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            orderList_ = java.util.Collections.unmodifiableList(orderList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.orderList_ = orderList_;
        } else {
          result.orderList_ = orderListBuilder_.build();
        }
        if (timeBuilder_ == null) {
          result.time_ = time_;
        } else {
          result.time_ = timeBuilder_.build();
        }
        result.status_ = status_;
        if (((bitField0_ & 0x00000002) != 0)) {
          data_ = data_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.data_ = data_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.amazaar.Protobuff.ConfirmOrderDeliveryPbOuterClass.ConfirmOrderDeliveryPb) {
          return mergeFrom((com.amazaar.Protobuff.ConfirmOrderDeliveryPbOuterClass.ConfirmOrderDeliveryPb)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.amazaar.Protobuff.ConfirmOrderDeliveryPbOuterClass.ConfirmOrderDeliveryPb other) {
        if (other == com.amazaar.Protobuff.ConfirmOrderDeliveryPbOuterClass.ConfirmOrderDeliveryPb.getDefaultInstance()) return this;
        if (!other.getCustomerId().isEmpty()) {
          customerId_ = other.customerId_;
          onChanged();
        }
        if (!other.getParentOrderId().isEmpty()) {
          parentOrderId_ = other.parentOrderId_;
          onChanged();
        }
        if (orderListBuilder_ == null) {
          if (!other.orderList_.isEmpty()) {
            if (orderList_.isEmpty()) {
              orderList_ = other.orderList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureOrderListIsMutable();
              orderList_.addAll(other.orderList_);
            }
            onChanged();
          }
        } else {
          if (!other.orderList_.isEmpty()) {
            if (orderListBuilder_.isEmpty()) {
              orderListBuilder_.dispose();
              orderListBuilder_ = null;
              orderList_ = other.orderList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              orderListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getOrderListFieldBuilder() : null;
            } else {
              orderListBuilder_.addAllMessages(other.orderList_);
            }
          }
        }
        if (other.hasTime()) {
          mergeTime(other.getTime());
        }
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        if (!other.data_.isEmpty()) {
          if (data_.isEmpty()) {
            data_ = other.data_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureDataIsMutable();
            data_.addAll(other.data_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.amazaar.Protobuff.ConfirmOrderDeliveryPbOuterClass.ConfirmOrderDeliveryPb parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.amazaar.Protobuff.ConfirmOrderDeliveryPbOuterClass.ConfirmOrderDeliveryPb) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object customerId_ = "";
      /**
       * <code>string customerId = 1;</code>
       * @return The customerId.
       */
      public java.lang.String getCustomerId() {
        java.lang.Object ref = customerId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          customerId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string customerId = 1;</code>
       * @return The bytes for customerId.
       */
      public com.google.protobuf.ByteString
          getCustomerIdBytes() {
        java.lang.Object ref = customerId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          customerId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string customerId = 1;</code>
       * @param value The customerId to set.
       * @return This builder for chaining.
       */
      public Builder setCustomerId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        customerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string customerId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCustomerId() {
        
        customerId_ = getDefaultInstance().getCustomerId();
        onChanged();
        return this;
      }
      /**
       * <code>string customerId = 1;</code>
       * @param value The bytes for customerId to set.
       * @return This builder for chaining.
       */
      public Builder setCustomerIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        customerId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object parentOrderId_ = "";
      /**
       * <code>string parentOrderId = 2;</code>
       * @return The parentOrderId.
       */
      public java.lang.String getParentOrderId() {
        java.lang.Object ref = parentOrderId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          parentOrderId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string parentOrderId = 2;</code>
       * @return The bytes for parentOrderId.
       */
      public com.google.protobuf.ByteString
          getParentOrderIdBytes() {
        java.lang.Object ref = parentOrderId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          parentOrderId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string parentOrderId = 2;</code>
       * @param value The parentOrderId to set.
       * @return This builder for chaining.
       */
      public Builder setParentOrderId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        parentOrderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string parentOrderId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearParentOrderId() {
        
        parentOrderId_ = getDefaultInstance().getParentOrderId();
        onChanged();
        return this;
      }
      /**
       * <code>string parentOrderId = 2;</code>
       * @param value The bytes for parentOrderId to set.
       * @return This builder for chaining.
       */
      public Builder setParentOrderIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        parentOrderId_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.amazaar.Protobuff.BuyPbOuterClass.BuyPb> orderList_ =
        java.util.Collections.emptyList();
      private void ensureOrderListIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          orderList_ = new java.util.ArrayList<com.amazaar.Protobuff.BuyPbOuterClass.BuyPb>(orderList_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.amazaar.Protobuff.BuyPbOuterClass.BuyPb, com.amazaar.Protobuff.BuyPbOuterClass.BuyPb.Builder, com.amazaar.Protobuff.BuyPbOuterClass.BuyPbOrBuilder> orderListBuilder_;

      /**
       * <code>repeated .com.amazaar.Protobuff.BuyPb orderList = 3;</code>
       */
      public java.util.List<com.amazaar.Protobuff.BuyPbOuterClass.BuyPb> getOrderListList() {
        if (orderListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(orderList_);
        } else {
          return orderListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.amazaar.Protobuff.BuyPb orderList = 3;</code>
       */
      public int getOrderListCount() {
        if (orderListBuilder_ == null) {
          return orderList_.size();
        } else {
          return orderListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.amazaar.Protobuff.BuyPb orderList = 3;</code>
       */
      public com.amazaar.Protobuff.BuyPbOuterClass.BuyPb getOrderList(int index) {
        if (orderListBuilder_ == null) {
          return orderList_.get(index);
        } else {
          return orderListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.amazaar.Protobuff.BuyPb orderList = 3;</code>
       */
      public Builder setOrderList(
          int index, com.amazaar.Protobuff.BuyPbOuterClass.BuyPb value) {
        if (orderListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrderListIsMutable();
          orderList_.set(index, value);
          onChanged();
        } else {
          orderListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.amazaar.Protobuff.BuyPb orderList = 3;</code>
       */
      public Builder setOrderList(
          int index, com.amazaar.Protobuff.BuyPbOuterClass.BuyPb.Builder builderForValue) {
        if (orderListBuilder_ == null) {
          ensureOrderListIsMutable();
          orderList_.set(index, builderForValue.build());
          onChanged();
        } else {
          orderListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.amazaar.Protobuff.BuyPb orderList = 3;</code>
       */
      public Builder addOrderList(com.amazaar.Protobuff.BuyPbOuterClass.BuyPb value) {
        if (orderListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrderListIsMutable();
          orderList_.add(value);
          onChanged();
        } else {
          orderListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.amazaar.Protobuff.BuyPb orderList = 3;</code>
       */
      public Builder addOrderList(
          int index, com.amazaar.Protobuff.BuyPbOuterClass.BuyPb value) {
        if (orderListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrderListIsMutable();
          orderList_.add(index, value);
          onChanged();
        } else {
          orderListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.amazaar.Protobuff.BuyPb orderList = 3;</code>
       */
      public Builder addOrderList(
          com.amazaar.Protobuff.BuyPbOuterClass.BuyPb.Builder builderForValue) {
        if (orderListBuilder_ == null) {
          ensureOrderListIsMutable();
          orderList_.add(builderForValue.build());
          onChanged();
        } else {
          orderListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.amazaar.Protobuff.BuyPb orderList = 3;</code>
       */
      public Builder addOrderList(
          int index, com.amazaar.Protobuff.BuyPbOuterClass.BuyPb.Builder builderForValue) {
        if (orderListBuilder_ == null) {
          ensureOrderListIsMutable();
          orderList_.add(index, builderForValue.build());
          onChanged();
        } else {
          orderListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.amazaar.Protobuff.BuyPb orderList = 3;</code>
       */
      public Builder addAllOrderList(
          java.lang.Iterable<? extends com.amazaar.Protobuff.BuyPbOuterClass.BuyPb> values) {
        if (orderListBuilder_ == null) {
          ensureOrderListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, orderList_);
          onChanged();
        } else {
          orderListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.amazaar.Protobuff.BuyPb orderList = 3;</code>
       */
      public Builder clearOrderList() {
        if (orderListBuilder_ == null) {
          orderList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          orderListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.amazaar.Protobuff.BuyPb orderList = 3;</code>
       */
      public Builder removeOrderList(int index) {
        if (orderListBuilder_ == null) {
          ensureOrderListIsMutable();
          orderList_.remove(index);
          onChanged();
        } else {
          orderListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.amazaar.Protobuff.BuyPb orderList = 3;</code>
       */
      public com.amazaar.Protobuff.BuyPbOuterClass.BuyPb.Builder getOrderListBuilder(
          int index) {
        return getOrderListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.amazaar.Protobuff.BuyPb orderList = 3;</code>
       */
      public com.amazaar.Protobuff.BuyPbOuterClass.BuyPbOrBuilder getOrderListOrBuilder(
          int index) {
        if (orderListBuilder_ == null) {
          return orderList_.get(index);  } else {
          return orderListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.amazaar.Protobuff.BuyPb orderList = 3;</code>
       */
      public java.util.List<? extends com.amazaar.Protobuff.BuyPbOuterClass.BuyPbOrBuilder> 
           getOrderListOrBuilderList() {
        if (orderListBuilder_ != null) {
          return orderListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(orderList_);
        }
      }
      /**
       * <code>repeated .com.amazaar.Protobuff.BuyPb orderList = 3;</code>
       */
      public com.amazaar.Protobuff.BuyPbOuterClass.BuyPb.Builder addOrderListBuilder() {
        return getOrderListFieldBuilder().addBuilder(
            com.amazaar.Protobuff.BuyPbOuterClass.BuyPb.getDefaultInstance());
      }
      /**
       * <code>repeated .com.amazaar.Protobuff.BuyPb orderList = 3;</code>
       */
      public com.amazaar.Protobuff.BuyPbOuterClass.BuyPb.Builder addOrderListBuilder(
          int index) {
        return getOrderListFieldBuilder().addBuilder(
            index, com.amazaar.Protobuff.BuyPbOuterClass.BuyPb.getDefaultInstance());
      }
      /**
       * <code>repeated .com.amazaar.Protobuff.BuyPb orderList = 3;</code>
       */
      public java.util.List<com.amazaar.Protobuff.BuyPbOuterClass.BuyPb.Builder> 
           getOrderListBuilderList() {
        return getOrderListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.amazaar.Protobuff.BuyPbOuterClass.BuyPb, com.amazaar.Protobuff.BuyPbOuterClass.BuyPb.Builder, com.amazaar.Protobuff.BuyPbOuterClass.BuyPbOrBuilder> 
          getOrderListFieldBuilder() {
        if (orderListBuilder_ == null) {
          orderListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.amazaar.Protobuff.BuyPbOuterClass.BuyPb, com.amazaar.Protobuff.BuyPbOuterClass.BuyPb.Builder, com.amazaar.Protobuff.BuyPbOuterClass.BuyPbOrBuilder>(
                  orderList_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          orderList_ = null;
        }
        return orderListBuilder_;
      }

      private com.amazaar.Protobuff.TimePbOuterClass.TimePb time_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.amazaar.Protobuff.TimePbOuterClass.TimePb, com.amazaar.Protobuff.TimePbOuterClass.TimePb.Builder, com.amazaar.Protobuff.TimePbOuterClass.TimePbOrBuilder> timeBuilder_;
      /**
       * <code>.com.amazaar.Protobuff.TimePb time = 4;</code>
       * @return Whether the time field is set.
       */
      public boolean hasTime() {
        return timeBuilder_ != null || time_ != null;
      }
      /**
       * <code>.com.amazaar.Protobuff.TimePb time = 4;</code>
       * @return The time.
       */
      public com.amazaar.Protobuff.TimePbOuterClass.TimePb getTime() {
        if (timeBuilder_ == null) {
          return time_ == null ? com.amazaar.Protobuff.TimePbOuterClass.TimePb.getDefaultInstance() : time_;
        } else {
          return timeBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.amazaar.Protobuff.TimePb time = 4;</code>
       */
      public Builder setTime(com.amazaar.Protobuff.TimePbOuterClass.TimePb value) {
        if (timeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          time_ = value;
          onChanged();
        } else {
          timeBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.amazaar.Protobuff.TimePb time = 4;</code>
       */
      public Builder setTime(
          com.amazaar.Protobuff.TimePbOuterClass.TimePb.Builder builderForValue) {
        if (timeBuilder_ == null) {
          time_ = builderForValue.build();
          onChanged();
        } else {
          timeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.amazaar.Protobuff.TimePb time = 4;</code>
       */
      public Builder mergeTime(com.amazaar.Protobuff.TimePbOuterClass.TimePb value) {
        if (timeBuilder_ == null) {
          if (time_ != null) {
            time_ =
              com.amazaar.Protobuff.TimePbOuterClass.TimePb.newBuilder(time_).mergeFrom(value).buildPartial();
          } else {
            time_ = value;
          }
          onChanged();
        } else {
          timeBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.amazaar.Protobuff.TimePb time = 4;</code>
       */
      public Builder clearTime() {
        if (timeBuilder_ == null) {
          time_ = null;
          onChanged();
        } else {
          time_ = null;
          timeBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.amazaar.Protobuff.TimePb time = 4;</code>
       */
      public com.amazaar.Protobuff.TimePbOuterClass.TimePb.Builder getTimeBuilder() {
        
        onChanged();
        return getTimeFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.amazaar.Protobuff.TimePb time = 4;</code>
       */
      public com.amazaar.Protobuff.TimePbOuterClass.TimePbOrBuilder getTimeOrBuilder() {
        if (timeBuilder_ != null) {
          return timeBuilder_.getMessageOrBuilder();
        } else {
          return time_ == null ?
              com.amazaar.Protobuff.TimePbOuterClass.TimePb.getDefaultInstance() : time_;
        }
      }
      /**
       * <code>.com.amazaar.Protobuff.TimePb time = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.amazaar.Protobuff.TimePbOuterClass.TimePb, com.amazaar.Protobuff.TimePbOuterClass.TimePb.Builder, com.amazaar.Protobuff.TimePbOuterClass.TimePbOrBuilder> 
          getTimeFieldBuilder() {
        if (timeBuilder_ == null) {
          timeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.amazaar.Protobuff.TimePbOuterClass.TimePb, com.amazaar.Protobuff.TimePbOuterClass.TimePb.Builder, com.amazaar.Protobuff.TimePbOuterClass.TimePbOrBuilder>(
                  getTime(),
                  getParentForChildren(),
                  isClean());
          time_ = null;
        }
        return timeBuilder_;
      }

      private int status_ = 0;
      /**
       * <code>.com.amazaar.Protobuff.IsOrderedPlacedEnum status = 5;</code>
       * @return The enum numeric value on the wire for status.
       */
      @java.lang.Override public int getStatusValue() {
        return status_;
      }
      /**
       * <code>.com.amazaar.Protobuff.IsOrderedPlacedEnum status = 5;</code>
       * @param value The enum numeric value on the wire for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusValue(int value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.amazaar.Protobuff.IsOrderedPlacedEnum status = 5;</code>
       * @return The status.
       */
      @java.lang.Override
      public com.amazaar.Protobuff.BuyPbOuterClass.IsOrderedPlacedEnum getStatus() {
        @SuppressWarnings("deprecation")
        com.amazaar.Protobuff.BuyPbOuterClass.IsOrderedPlacedEnum result = com.amazaar.Protobuff.BuyPbOuterClass.IsOrderedPlacedEnum.valueOf(status_);
        return result == null ? com.amazaar.Protobuff.BuyPbOuterClass.IsOrderedPlacedEnum.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.amazaar.Protobuff.IsOrderedPlacedEnum status = 5;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(com.amazaar.Protobuff.BuyPbOuterClass.IsOrderedPlacedEnum value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.amazaar.Protobuff.IsOrderedPlacedEnum status = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList data_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          data_ = new com.google.protobuf.LazyStringArrayList(data_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string data = 6;</code>
       * @return A list containing the data.
       */
      public com.google.protobuf.ProtocolStringList
          getDataList() {
        return data_.getUnmodifiableView();
      }
      /**
       * <code>repeated string data = 6;</code>
       * @return The count of data.
       */
      public int getDataCount() {
        return data_.size();
      }
      /**
       * <code>repeated string data = 6;</code>
       * @param index The index of the element to return.
       * @return The data at the given index.
       */
      public java.lang.String getData(int index) {
        return data_.get(index);
      }
      /**
       * <code>repeated string data = 6;</code>
       * @param index The index of the value to return.
       * @return The bytes of the data at the given index.
       */
      public com.google.protobuf.ByteString
          getDataBytes(int index) {
        return data_.getByteString(index);
      }
      /**
       * <code>repeated string data = 6;</code>
       * @param index The index to set the value at.
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDataIsMutable();
        data_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string data = 6;</code>
       * @param value The data to add.
       * @return This builder for chaining.
       */
      public Builder addData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDataIsMutable();
        data_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string data = 6;</code>
       * @param values The data to add.
       * @return This builder for chaining.
       */
      public Builder addAllData(
          java.lang.Iterable<java.lang.String> values) {
        ensureDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, data_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string data = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        data_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string data = 6;</code>
       * @param value The bytes of the data to add.
       * @return This builder for chaining.
       */
      public Builder addDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureDataIsMutable();
        data_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.amazaar.Protobuff.ConfirmOrderDeliveryPb)
    }

    // @@protoc_insertion_point(class_scope:com.amazaar.Protobuff.ConfirmOrderDeliveryPb)
    private static final com.amazaar.Protobuff.ConfirmOrderDeliveryPbOuterClass.ConfirmOrderDeliveryPb DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.amazaar.Protobuff.ConfirmOrderDeliveryPbOuterClass.ConfirmOrderDeliveryPb();
    }

    public static com.amazaar.Protobuff.ConfirmOrderDeliveryPbOuterClass.ConfirmOrderDeliveryPb getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConfirmOrderDeliveryPb>
        PARSER = new com.google.protobuf.AbstractParser<ConfirmOrderDeliveryPb>() {
      @java.lang.Override
      public ConfirmOrderDeliveryPb parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConfirmOrderDeliveryPb(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConfirmOrderDeliveryPb> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConfirmOrderDeliveryPb> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.amazaar.Protobuff.ConfirmOrderDeliveryPbOuterClass.ConfirmOrderDeliveryPb getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_amazaar_Protobuff_ConfirmOrderDeliveryPb_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_amazaar_Protobuff_ConfirmOrderDeliveryPb_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034confirmOrderDeliveryPb.proto\022\025com.amaz" +
      "aar.Protobuff\032\014timePb.proto\032\013buyPb.proto" +
      "\"\353\001\n\026ConfirmOrderDeliveryPb\022\022\n\ncustomerI" +
      "d\030\001 \001(\t\022\025\n\rparentOrderId\030\002 \001(\t\022/\n\torderL" +
      "ist\030\003 \003(\0132\034.com.amazaar.Protobuff.BuyPb\022" +
      "+\n\004time\030\004 \001(\0132\035.com.amazaar.Protobuff.Ti" +
      "mePb\022:\n\006status\030\005 \001(\0162*.com.amazaar.Proto" +
      "buff.IsOrderedPlacedEnum\022\014\n\004data\030\006 \003(\tb\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.amazaar.Protobuff.TimePbOuterClass.getDescriptor(),
          com.amazaar.Protobuff.BuyPbOuterClass.getDescriptor(),
        });
    internal_static_com_amazaar_Protobuff_ConfirmOrderDeliveryPb_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_amazaar_Protobuff_ConfirmOrderDeliveryPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_amazaar_Protobuff_ConfirmOrderDeliveryPb_descriptor,
        new java.lang.String[] { "CustomerId", "ParentOrderId", "OrderList", "Time", "Status", "Data", });
    com.amazaar.Protobuff.TimePbOuterClass.getDescriptor();
    com.amazaar.Protobuff.BuyPbOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
