// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contactDetailPb.proto

package com.amazaar.Protobuff;

public final class ContactDetailPbOuterClass {
  private ContactDetailPbOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EmailPbOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.amazaar.Protobuff.EmailPb)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string localPart = 1;</code>
     * @return The localPart.
     */
    java.lang.String getLocalPart();
    /**
     * <code>string localPart = 1;</code>
     * @return The bytes for localPart.
     */
    com.google.protobuf.ByteString
        getLocalPartBytes();

    /**
     * <code>string domainPart = 2;</code>
     * @return The domainPart.
     */
    java.lang.String getDomainPart();
    /**
     * <code>string domainPart = 2;</code>
     * @return The bytes for domainPart.
     */
    com.google.protobuf.ByteString
        getDomainPartBytes();
  }
  /**
   * Protobuf type {@code com.amazaar.Protobuff.EmailPb}
   */
  public static final class EmailPb extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.amazaar.Protobuff.EmailPb)
      EmailPbOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EmailPb.newBuilder() to construct.
    private EmailPb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EmailPb() {
      localPart_ = "";
      domainPart_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EmailPb();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EmailPb(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              localPart_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              domainPart_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.amazaar.Protobuff.ContactDetailPbOuterClass.internal_static_com_amazaar_Protobuff_EmailPb_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.amazaar.Protobuff.ContactDetailPbOuterClass.internal_static_com_amazaar_Protobuff_EmailPb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb.class, com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb.Builder.class);
    }

    public static final int LOCALPART_FIELD_NUMBER = 1;
    private volatile java.lang.Object localPart_;
    /**
     * <code>string localPart = 1;</code>
     * @return The localPart.
     */
    @java.lang.Override
    public java.lang.String getLocalPart() {
      java.lang.Object ref = localPart_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        localPart_ = s;
        return s;
      }
    }
    /**
     * <code>string localPart = 1;</code>
     * @return The bytes for localPart.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLocalPartBytes() {
      java.lang.Object ref = localPart_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        localPart_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DOMAINPART_FIELD_NUMBER = 2;
    private volatile java.lang.Object domainPart_;
    /**
     * <code>string domainPart = 2;</code>
     * @return The domainPart.
     */
    @java.lang.Override
    public java.lang.String getDomainPart() {
      java.lang.Object ref = domainPart_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        domainPart_ = s;
        return s;
      }
    }
    /**
     * <code>string domainPart = 2;</code>
     * @return The bytes for domainPart.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDomainPartBytes() {
      java.lang.Object ref = domainPart_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        domainPart_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getLocalPartBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, localPart_);
      }
      if (!getDomainPartBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, domainPart_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getLocalPartBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, localPart_);
      }
      if (!getDomainPartBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, domainPart_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb)) {
        return super.equals(obj);
      }
      com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb other = (com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb) obj;

      if (!getLocalPart()
          .equals(other.getLocalPart())) return false;
      if (!getDomainPart()
          .equals(other.getDomainPart())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LOCALPART_FIELD_NUMBER;
      hash = (53 * hash) + getLocalPart().hashCode();
      hash = (37 * hash) + DOMAINPART_FIELD_NUMBER;
      hash = (53 * hash) + getDomainPart().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.amazaar.Protobuff.EmailPb}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.amazaar.Protobuff.EmailPb)
        com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPbOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.amazaar.Protobuff.ContactDetailPbOuterClass.internal_static_com_amazaar_Protobuff_EmailPb_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.amazaar.Protobuff.ContactDetailPbOuterClass.internal_static_com_amazaar_Protobuff_EmailPb_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb.class, com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb.Builder.class);
      }

      // Construct using com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        localPart_ = "";

        domainPart_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.amazaar.Protobuff.ContactDetailPbOuterClass.internal_static_com_amazaar_Protobuff_EmailPb_descriptor;
      }

      @java.lang.Override
      public com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb getDefaultInstanceForType() {
        return com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb.getDefaultInstance();
      }

      @java.lang.Override
      public com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb build() {
        com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb buildPartial() {
        com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb result = new com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb(this);
        result.localPart_ = localPart_;
        result.domainPart_ = domainPart_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb) {
          return mergeFrom((com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb other) {
        if (other == com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb.getDefaultInstance()) return this;
        if (!other.getLocalPart().isEmpty()) {
          localPart_ = other.localPart_;
          onChanged();
        }
        if (!other.getDomainPart().isEmpty()) {
          domainPart_ = other.domainPart_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object localPart_ = "";
      /**
       * <code>string localPart = 1;</code>
       * @return The localPart.
       */
      public java.lang.String getLocalPart() {
        java.lang.Object ref = localPart_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          localPart_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string localPart = 1;</code>
       * @return The bytes for localPart.
       */
      public com.google.protobuf.ByteString
          getLocalPartBytes() {
        java.lang.Object ref = localPart_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          localPart_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string localPart = 1;</code>
       * @param value The localPart to set.
       * @return This builder for chaining.
       */
      public Builder setLocalPart(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        localPart_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string localPart = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLocalPart() {
        
        localPart_ = getDefaultInstance().getLocalPart();
        onChanged();
        return this;
      }
      /**
       * <code>string localPart = 1;</code>
       * @param value The bytes for localPart to set.
       * @return This builder for chaining.
       */
      public Builder setLocalPartBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        localPart_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object domainPart_ = "";
      /**
       * <code>string domainPart = 2;</code>
       * @return The domainPart.
       */
      public java.lang.String getDomainPart() {
        java.lang.Object ref = domainPart_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          domainPart_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string domainPart = 2;</code>
       * @return The bytes for domainPart.
       */
      public com.google.protobuf.ByteString
          getDomainPartBytes() {
        java.lang.Object ref = domainPart_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          domainPart_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string domainPart = 2;</code>
       * @param value The domainPart to set.
       * @return This builder for chaining.
       */
      public Builder setDomainPart(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        domainPart_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string domainPart = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDomainPart() {
        
        domainPart_ = getDefaultInstance().getDomainPart();
        onChanged();
        return this;
      }
      /**
       * <code>string domainPart = 2;</code>
       * @param value The bytes for domainPart to set.
       * @return This builder for chaining.
       */
      public Builder setDomainPartBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        domainPart_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.amazaar.Protobuff.EmailPb)
    }

    // @@protoc_insertion_point(class_scope:com.amazaar.Protobuff.EmailPb)
    private static final com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb();
    }

    public static com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EmailPb>
        PARSER = new com.google.protobuf.AbstractParser<EmailPb>() {
      @java.lang.Override
      public EmailPb parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EmailPb(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EmailPb> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EmailPb> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MobilePbOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.amazaar.Protobuff.MobilePb)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string mobileNo = 1;</code>
     * @return The mobileNo.
     */
    java.lang.String getMobileNo();
    /**
     * <code>string mobileNo = 1;</code>
     * @return The bytes for mobileNo.
     */
    com.google.protobuf.ByteString
        getMobileNoBytes();
  }
  /**
   * Protobuf type {@code com.amazaar.Protobuff.MobilePb}
   */
  public static final class MobilePb extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.amazaar.Protobuff.MobilePb)
      MobilePbOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MobilePb.newBuilder() to construct.
    private MobilePb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MobilePb() {
      mobileNo_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MobilePb();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MobilePb(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              mobileNo_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.amazaar.Protobuff.ContactDetailPbOuterClass.internal_static_com_amazaar_Protobuff_MobilePb_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.amazaar.Protobuff.ContactDetailPbOuterClass.internal_static_com_amazaar_Protobuff_MobilePb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb.class, com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb.Builder.class);
    }

    public static final int MOBILENO_FIELD_NUMBER = 1;
    private volatile java.lang.Object mobileNo_;
    /**
     * <code>string mobileNo = 1;</code>
     * @return The mobileNo.
     */
    @java.lang.Override
    public java.lang.String getMobileNo() {
      java.lang.Object ref = mobileNo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mobileNo_ = s;
        return s;
      }
    }
    /**
     * <code>string mobileNo = 1;</code>
     * @return The bytes for mobileNo.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMobileNoBytes() {
      java.lang.Object ref = mobileNo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mobileNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMobileNoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, mobileNo_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMobileNoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, mobileNo_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb)) {
        return super.equals(obj);
      }
      com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb other = (com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb) obj;

      if (!getMobileNo()
          .equals(other.getMobileNo())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MOBILENO_FIELD_NUMBER;
      hash = (53 * hash) + getMobileNo().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.amazaar.Protobuff.MobilePb}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.amazaar.Protobuff.MobilePb)
        com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePbOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.amazaar.Protobuff.ContactDetailPbOuterClass.internal_static_com_amazaar_Protobuff_MobilePb_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.amazaar.Protobuff.ContactDetailPbOuterClass.internal_static_com_amazaar_Protobuff_MobilePb_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb.class, com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb.Builder.class);
      }

      // Construct using com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        mobileNo_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.amazaar.Protobuff.ContactDetailPbOuterClass.internal_static_com_amazaar_Protobuff_MobilePb_descriptor;
      }

      @java.lang.Override
      public com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb getDefaultInstanceForType() {
        return com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb.getDefaultInstance();
      }

      @java.lang.Override
      public com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb build() {
        com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb buildPartial() {
        com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb result = new com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb(this);
        result.mobileNo_ = mobileNo_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb) {
          return mergeFrom((com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb other) {
        if (other == com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb.getDefaultInstance()) return this;
        if (!other.getMobileNo().isEmpty()) {
          mobileNo_ = other.mobileNo_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object mobileNo_ = "";
      /**
       * <code>string mobileNo = 1;</code>
       * @return The mobileNo.
       */
      public java.lang.String getMobileNo() {
        java.lang.Object ref = mobileNo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mobileNo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string mobileNo = 1;</code>
       * @return The bytes for mobileNo.
       */
      public com.google.protobuf.ByteString
          getMobileNoBytes() {
        java.lang.Object ref = mobileNo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mobileNo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string mobileNo = 1;</code>
       * @param value The mobileNo to set.
       * @return This builder for chaining.
       */
      public Builder setMobileNo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mobileNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string mobileNo = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMobileNo() {
        
        mobileNo_ = getDefaultInstance().getMobileNo();
        onChanged();
        return this;
      }
      /**
       * <code>string mobileNo = 1;</code>
       * @param value The bytes for mobileNo to set.
       * @return This builder for chaining.
       */
      public Builder setMobileNoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mobileNo_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.amazaar.Protobuff.MobilePb)
    }

    // @@protoc_insertion_point(class_scope:com.amazaar.Protobuff.MobilePb)
    private static final com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb();
    }

    public static com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MobilePb>
        PARSER = new com.google.protobuf.AbstractParser<MobilePb>() {
      @java.lang.Override
      public MobilePb parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MobilePb(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MobilePb> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MobilePb> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ContactDetailPbOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.amazaar.Protobuff.ContactDetailPb)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.amazaar.Protobuff.EmailPb email = 1;</code>
     * @return Whether the email field is set.
     */
    boolean hasEmail();
    /**
     * <code>.com.amazaar.Protobuff.EmailPb email = 1;</code>
     * @return The email.
     */
    com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb getEmail();
    /**
     * <code>.com.amazaar.Protobuff.EmailPb email = 1;</code>
     */
    com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPbOrBuilder getEmailOrBuilder();

    /**
     * <code>.com.amazaar.Protobuff.MobilePb mobile = 2;</code>
     * @return Whether the mobile field is set.
     */
    boolean hasMobile();
    /**
     * <code>.com.amazaar.Protobuff.MobilePb mobile = 2;</code>
     * @return The mobile.
     */
    com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb getMobile();
    /**
     * <code>.com.amazaar.Protobuff.MobilePb mobile = 2;</code>
     */
    com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePbOrBuilder getMobileOrBuilder();
  }
  /**
   * Protobuf type {@code com.amazaar.Protobuff.ContactDetailPb}
   */
  public static final class ContactDetailPb extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.amazaar.Protobuff.ContactDetailPb)
      ContactDetailPbOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ContactDetailPb.newBuilder() to construct.
    private ContactDetailPb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ContactDetailPb() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ContactDetailPb();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ContactDetailPb(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb.Builder subBuilder = null;
              if (email_ != null) {
                subBuilder = email_.toBuilder();
              }
              email_ = input.readMessage(com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(email_);
                email_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb.Builder subBuilder = null;
              if (mobile_ != null) {
                subBuilder = mobile_.toBuilder();
              }
              mobile_ = input.readMessage(com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(mobile_);
                mobile_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.amazaar.Protobuff.ContactDetailPbOuterClass.internal_static_com_amazaar_Protobuff_ContactDetailPb_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.amazaar.Protobuff.ContactDetailPbOuterClass.internal_static_com_amazaar_Protobuff_ContactDetailPb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.amazaar.Protobuff.ContactDetailPbOuterClass.ContactDetailPb.class, com.amazaar.Protobuff.ContactDetailPbOuterClass.ContactDetailPb.Builder.class);
    }

    public static final int EMAIL_FIELD_NUMBER = 1;
    private com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb email_;
    /**
     * <code>.com.amazaar.Protobuff.EmailPb email = 1;</code>
     * @return Whether the email field is set.
     */
    @java.lang.Override
    public boolean hasEmail() {
      return email_ != null;
    }
    /**
     * <code>.com.amazaar.Protobuff.EmailPb email = 1;</code>
     * @return The email.
     */
    @java.lang.Override
    public com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb getEmail() {
      return email_ == null ? com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb.getDefaultInstance() : email_;
    }
    /**
     * <code>.com.amazaar.Protobuff.EmailPb email = 1;</code>
     */
    @java.lang.Override
    public com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPbOrBuilder getEmailOrBuilder() {
      return getEmail();
    }

    public static final int MOBILE_FIELD_NUMBER = 2;
    private com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb mobile_;
    /**
     * <code>.com.amazaar.Protobuff.MobilePb mobile = 2;</code>
     * @return Whether the mobile field is set.
     */
    @java.lang.Override
    public boolean hasMobile() {
      return mobile_ != null;
    }
    /**
     * <code>.com.amazaar.Protobuff.MobilePb mobile = 2;</code>
     * @return The mobile.
     */
    @java.lang.Override
    public com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb getMobile() {
      return mobile_ == null ? com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb.getDefaultInstance() : mobile_;
    }
    /**
     * <code>.com.amazaar.Protobuff.MobilePb mobile = 2;</code>
     */
    @java.lang.Override
    public com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePbOrBuilder getMobileOrBuilder() {
      return getMobile();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (email_ != null) {
        output.writeMessage(1, getEmail());
      }
      if (mobile_ != null) {
        output.writeMessage(2, getMobile());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (email_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getEmail());
      }
      if (mobile_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getMobile());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.amazaar.Protobuff.ContactDetailPbOuterClass.ContactDetailPb)) {
        return super.equals(obj);
      }
      com.amazaar.Protobuff.ContactDetailPbOuterClass.ContactDetailPb other = (com.amazaar.Protobuff.ContactDetailPbOuterClass.ContactDetailPb) obj;

      if (hasEmail() != other.hasEmail()) return false;
      if (hasEmail()) {
        if (!getEmail()
            .equals(other.getEmail())) return false;
      }
      if (hasMobile() != other.hasMobile()) return false;
      if (hasMobile()) {
        if (!getMobile()
            .equals(other.getMobile())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasEmail()) {
        hash = (37 * hash) + EMAIL_FIELD_NUMBER;
        hash = (53 * hash) + getEmail().hashCode();
      }
      if (hasMobile()) {
        hash = (37 * hash) + MOBILE_FIELD_NUMBER;
        hash = (53 * hash) + getMobile().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.amazaar.Protobuff.ContactDetailPbOuterClass.ContactDetailPb parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.amazaar.Protobuff.ContactDetailPbOuterClass.ContactDetailPb parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.amazaar.Protobuff.ContactDetailPbOuterClass.ContactDetailPb parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.amazaar.Protobuff.ContactDetailPbOuterClass.ContactDetailPb parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.amazaar.Protobuff.ContactDetailPbOuterClass.ContactDetailPb parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.amazaar.Protobuff.ContactDetailPbOuterClass.ContactDetailPb parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.amazaar.Protobuff.ContactDetailPbOuterClass.ContactDetailPb parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.amazaar.Protobuff.ContactDetailPbOuterClass.ContactDetailPb parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.amazaar.Protobuff.ContactDetailPbOuterClass.ContactDetailPb parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.amazaar.Protobuff.ContactDetailPbOuterClass.ContactDetailPb parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.amazaar.Protobuff.ContactDetailPbOuterClass.ContactDetailPb parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.amazaar.Protobuff.ContactDetailPbOuterClass.ContactDetailPb parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.amazaar.Protobuff.ContactDetailPbOuterClass.ContactDetailPb prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.amazaar.Protobuff.ContactDetailPb}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.amazaar.Protobuff.ContactDetailPb)
        com.amazaar.Protobuff.ContactDetailPbOuterClass.ContactDetailPbOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.amazaar.Protobuff.ContactDetailPbOuterClass.internal_static_com_amazaar_Protobuff_ContactDetailPb_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.amazaar.Protobuff.ContactDetailPbOuterClass.internal_static_com_amazaar_Protobuff_ContactDetailPb_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.amazaar.Protobuff.ContactDetailPbOuterClass.ContactDetailPb.class, com.amazaar.Protobuff.ContactDetailPbOuterClass.ContactDetailPb.Builder.class);
      }

      // Construct using com.amazaar.Protobuff.ContactDetailPbOuterClass.ContactDetailPb.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (emailBuilder_ == null) {
          email_ = null;
        } else {
          email_ = null;
          emailBuilder_ = null;
        }
        if (mobileBuilder_ == null) {
          mobile_ = null;
        } else {
          mobile_ = null;
          mobileBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.amazaar.Protobuff.ContactDetailPbOuterClass.internal_static_com_amazaar_Protobuff_ContactDetailPb_descriptor;
      }

      @java.lang.Override
      public com.amazaar.Protobuff.ContactDetailPbOuterClass.ContactDetailPb getDefaultInstanceForType() {
        return com.amazaar.Protobuff.ContactDetailPbOuterClass.ContactDetailPb.getDefaultInstance();
      }

      @java.lang.Override
      public com.amazaar.Protobuff.ContactDetailPbOuterClass.ContactDetailPb build() {
        com.amazaar.Protobuff.ContactDetailPbOuterClass.ContactDetailPb result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.amazaar.Protobuff.ContactDetailPbOuterClass.ContactDetailPb buildPartial() {
        com.amazaar.Protobuff.ContactDetailPbOuterClass.ContactDetailPb result = new com.amazaar.Protobuff.ContactDetailPbOuterClass.ContactDetailPb(this);
        if (emailBuilder_ == null) {
          result.email_ = email_;
        } else {
          result.email_ = emailBuilder_.build();
        }
        if (mobileBuilder_ == null) {
          result.mobile_ = mobile_;
        } else {
          result.mobile_ = mobileBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.amazaar.Protobuff.ContactDetailPbOuterClass.ContactDetailPb) {
          return mergeFrom((com.amazaar.Protobuff.ContactDetailPbOuterClass.ContactDetailPb)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.amazaar.Protobuff.ContactDetailPbOuterClass.ContactDetailPb other) {
        if (other == com.amazaar.Protobuff.ContactDetailPbOuterClass.ContactDetailPb.getDefaultInstance()) return this;
        if (other.hasEmail()) {
          mergeEmail(other.getEmail());
        }
        if (other.hasMobile()) {
          mergeMobile(other.getMobile());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.amazaar.Protobuff.ContactDetailPbOuterClass.ContactDetailPb parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.amazaar.Protobuff.ContactDetailPbOuterClass.ContactDetailPb) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb email_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb, com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb.Builder, com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPbOrBuilder> emailBuilder_;
      /**
       * <code>.com.amazaar.Protobuff.EmailPb email = 1;</code>
       * @return Whether the email field is set.
       */
      public boolean hasEmail() {
        return emailBuilder_ != null || email_ != null;
      }
      /**
       * <code>.com.amazaar.Protobuff.EmailPb email = 1;</code>
       * @return The email.
       */
      public com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb getEmail() {
        if (emailBuilder_ == null) {
          return email_ == null ? com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb.getDefaultInstance() : email_;
        } else {
          return emailBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.amazaar.Protobuff.EmailPb email = 1;</code>
       */
      public Builder setEmail(com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb value) {
        if (emailBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          email_ = value;
          onChanged();
        } else {
          emailBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.amazaar.Protobuff.EmailPb email = 1;</code>
       */
      public Builder setEmail(
          com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb.Builder builderForValue) {
        if (emailBuilder_ == null) {
          email_ = builderForValue.build();
          onChanged();
        } else {
          emailBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.amazaar.Protobuff.EmailPb email = 1;</code>
       */
      public Builder mergeEmail(com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb value) {
        if (emailBuilder_ == null) {
          if (email_ != null) {
            email_ =
              com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb.newBuilder(email_).mergeFrom(value).buildPartial();
          } else {
            email_ = value;
          }
          onChanged();
        } else {
          emailBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.amazaar.Protobuff.EmailPb email = 1;</code>
       */
      public Builder clearEmail() {
        if (emailBuilder_ == null) {
          email_ = null;
          onChanged();
        } else {
          email_ = null;
          emailBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.amazaar.Protobuff.EmailPb email = 1;</code>
       */
      public com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb.Builder getEmailBuilder() {
        
        onChanged();
        return getEmailFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.amazaar.Protobuff.EmailPb email = 1;</code>
       */
      public com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPbOrBuilder getEmailOrBuilder() {
        if (emailBuilder_ != null) {
          return emailBuilder_.getMessageOrBuilder();
        } else {
          return email_ == null ?
              com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb.getDefaultInstance() : email_;
        }
      }
      /**
       * <code>.com.amazaar.Protobuff.EmailPb email = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb, com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb.Builder, com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPbOrBuilder> 
          getEmailFieldBuilder() {
        if (emailBuilder_ == null) {
          emailBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb, com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPb.Builder, com.amazaar.Protobuff.ContactDetailPbOuterClass.EmailPbOrBuilder>(
                  getEmail(),
                  getParentForChildren(),
                  isClean());
          email_ = null;
        }
        return emailBuilder_;
      }

      private com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb mobile_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb, com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb.Builder, com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePbOrBuilder> mobileBuilder_;
      /**
       * <code>.com.amazaar.Protobuff.MobilePb mobile = 2;</code>
       * @return Whether the mobile field is set.
       */
      public boolean hasMobile() {
        return mobileBuilder_ != null || mobile_ != null;
      }
      /**
       * <code>.com.amazaar.Protobuff.MobilePb mobile = 2;</code>
       * @return The mobile.
       */
      public com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb getMobile() {
        if (mobileBuilder_ == null) {
          return mobile_ == null ? com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb.getDefaultInstance() : mobile_;
        } else {
          return mobileBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.amazaar.Protobuff.MobilePb mobile = 2;</code>
       */
      public Builder setMobile(com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb value) {
        if (mobileBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          mobile_ = value;
          onChanged();
        } else {
          mobileBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.amazaar.Protobuff.MobilePb mobile = 2;</code>
       */
      public Builder setMobile(
          com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb.Builder builderForValue) {
        if (mobileBuilder_ == null) {
          mobile_ = builderForValue.build();
          onChanged();
        } else {
          mobileBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.amazaar.Protobuff.MobilePb mobile = 2;</code>
       */
      public Builder mergeMobile(com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb value) {
        if (mobileBuilder_ == null) {
          if (mobile_ != null) {
            mobile_ =
              com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb.newBuilder(mobile_).mergeFrom(value).buildPartial();
          } else {
            mobile_ = value;
          }
          onChanged();
        } else {
          mobileBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.amazaar.Protobuff.MobilePb mobile = 2;</code>
       */
      public Builder clearMobile() {
        if (mobileBuilder_ == null) {
          mobile_ = null;
          onChanged();
        } else {
          mobile_ = null;
          mobileBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.amazaar.Protobuff.MobilePb mobile = 2;</code>
       */
      public com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb.Builder getMobileBuilder() {
        
        onChanged();
        return getMobileFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.amazaar.Protobuff.MobilePb mobile = 2;</code>
       */
      public com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePbOrBuilder getMobileOrBuilder() {
        if (mobileBuilder_ != null) {
          return mobileBuilder_.getMessageOrBuilder();
        } else {
          return mobile_ == null ?
              com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb.getDefaultInstance() : mobile_;
        }
      }
      /**
       * <code>.com.amazaar.Protobuff.MobilePb mobile = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb, com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb.Builder, com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePbOrBuilder> 
          getMobileFieldBuilder() {
        if (mobileBuilder_ == null) {
          mobileBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb, com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePb.Builder, com.amazaar.Protobuff.ContactDetailPbOuterClass.MobilePbOrBuilder>(
                  getMobile(),
                  getParentForChildren(),
                  isClean());
          mobile_ = null;
        }
        return mobileBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.amazaar.Protobuff.ContactDetailPb)
    }

    // @@protoc_insertion_point(class_scope:com.amazaar.Protobuff.ContactDetailPb)
    private static final com.amazaar.Protobuff.ContactDetailPbOuterClass.ContactDetailPb DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.amazaar.Protobuff.ContactDetailPbOuterClass.ContactDetailPb();
    }

    public static com.amazaar.Protobuff.ContactDetailPbOuterClass.ContactDetailPb getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ContactDetailPb>
        PARSER = new com.google.protobuf.AbstractParser<ContactDetailPb>() {
      @java.lang.Override
      public ContactDetailPb parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ContactDetailPb(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ContactDetailPb> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ContactDetailPb> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.amazaar.Protobuff.ContactDetailPbOuterClass.ContactDetailPb getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_amazaar_Protobuff_EmailPb_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_amazaar_Protobuff_EmailPb_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_amazaar_Protobuff_MobilePb_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_amazaar_Protobuff_MobilePb_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_amazaar_Protobuff_ContactDetailPb_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_amazaar_Protobuff_ContactDetailPb_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025contactDetailPb.proto\022\025com.amazaar.Pro" +
      "tobuff\"0\n\007EmailPb\022\021\n\tlocalPart\030\001 \001(\t\022\022\n\n" +
      "domainPart\030\002 \001(\t\"\034\n\010MobilePb\022\020\n\010mobileNo" +
      "\030\001 \001(\t\"q\n\017ContactDetailPb\022-\n\005email\030\001 \001(\013" +
      "2\036.com.amazaar.Protobuff.EmailPb\022/\n\006mobi" +
      "le\030\002 \001(\0132\037.com.amazaar.Protobuff.MobileP" +
      "bb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_amazaar_Protobuff_EmailPb_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_amazaar_Protobuff_EmailPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_amazaar_Protobuff_EmailPb_descriptor,
        new java.lang.String[] { "LocalPart", "DomainPart", });
    internal_static_com_amazaar_Protobuff_MobilePb_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_amazaar_Protobuff_MobilePb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_amazaar_Protobuff_MobilePb_descriptor,
        new java.lang.String[] { "MobileNo", });
    internal_static_com_amazaar_Protobuff_ContactDetailPb_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_amazaar_Protobuff_ContactDetailPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_amazaar_Protobuff_ContactDetailPb_descriptor,
        new java.lang.String[] { "Email", "Mobile", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
