// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entityPb.proto

package com.amazaar.Protobuff;

public final class EntityPbOuterClass {
  private EntityPbOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.amazaar.Protobuff.StatusEnum}
   */
  public enum StatusEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN_STATUS = 0;</code>
     */
    UNKNOWN_STATUS(0),
    /**
     * <code>ACTIVE = 1;</code>
     */
    ACTIVE(1),
    /**
     * <code>DELETED = 2;</code>
     */
    DELETED(2),
    /**
     * <code>SUSPUNDED = 3;</code>
     */
    SUSPUNDED(3),
    /**
     * <code>BLOCKED = 4;</code>
     */
    BLOCKED(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN_STATUS = 0;</code>
     */
    public static final int UNKNOWN_STATUS_VALUE = 0;
    /**
     * <code>ACTIVE = 1;</code>
     */
    public static final int ACTIVE_VALUE = 1;
    /**
     * <code>DELETED = 2;</code>
     */
    public static final int DELETED_VALUE = 2;
    /**
     * <code>SUSPUNDED = 3;</code>
     */
    public static final int SUSPUNDED_VALUE = 3;
    /**
     * <code>BLOCKED = 4;</code>
     */
    public static final int BLOCKED_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static StatusEnum valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static StatusEnum forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN_STATUS;
        case 1: return ACTIVE;
        case 2: return DELETED;
        case 3: return SUSPUNDED;
        case 4: return BLOCKED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<StatusEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        StatusEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<StatusEnum>() {
            public StatusEnum findValueByNumber(int number) {
              return StatusEnum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.amazaar.Protobuff.EntityPbOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final StatusEnum[] VALUES = values();

    public static StatusEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private StatusEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.amazaar.Protobuff.StatusEnum)
  }

  public interface EntityPbOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.amazaar.Protobuff.EntityPb)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>.com.amazaar.Protobuff.StatusEnum lifeTime = 3;</code>
     * @return The enum numeric value on the wire for lifeTime.
     */
    int getLifeTimeValue();
    /**
     * <code>.com.amazaar.Protobuff.StatusEnum lifeTime = 3;</code>
     * @return The lifeTime.
     */
    com.amazaar.Protobuff.EntityPbOuterClass.StatusEnum getLifeTime();

    /**
     * <code>.com.amazaar.Protobuff.LocalePb locale = 4;</code>
     * @return Whether the locale field is set.
     */
    boolean hasLocale();
    /**
     * <code>.com.amazaar.Protobuff.LocalePb locale = 4;</code>
     * @return The locale.
     */
    com.amazaar.Protobuff.EntityPbOuterClass.LocalePb getLocale();
    /**
     * <code>.com.amazaar.Protobuff.LocalePb locale = 4;</code>
     */
    com.amazaar.Protobuff.EntityPbOuterClass.LocalePbOrBuilder getLocaleOrBuilder();
  }
  /**
   * Protobuf type {@code com.amazaar.Protobuff.EntityPb}
   */
  public static final class EntityPb extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.amazaar.Protobuff.EntityPb)
      EntityPbOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EntityPb.newBuilder() to construct.
    private EntityPb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EntityPb() {
      id_ = "";
      lifeTime_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EntityPb();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EntityPb(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              lifeTime_ = rawValue;
              break;
            }
            case 34: {
              com.amazaar.Protobuff.EntityPbOuterClass.LocalePb.Builder subBuilder = null;
              if (locale_ != null) {
                subBuilder = locale_.toBuilder();
              }
              locale_ = input.readMessage(com.amazaar.Protobuff.EntityPbOuterClass.LocalePb.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(locale_);
                locale_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.amazaar.Protobuff.EntityPbOuterClass.internal_static_com_amazaar_Protobuff_EntityPb_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.amazaar.Protobuff.EntityPbOuterClass.internal_static_com_amazaar_Protobuff_EntityPb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.amazaar.Protobuff.EntityPbOuterClass.EntityPb.class, com.amazaar.Protobuff.EntityPbOuterClass.EntityPb.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LIFETIME_FIELD_NUMBER = 3;
    private int lifeTime_;
    /**
     * <code>.com.amazaar.Protobuff.StatusEnum lifeTime = 3;</code>
     * @return The enum numeric value on the wire for lifeTime.
     */
    @java.lang.Override public int getLifeTimeValue() {
      return lifeTime_;
    }
    /**
     * <code>.com.amazaar.Protobuff.StatusEnum lifeTime = 3;</code>
     * @return The lifeTime.
     */
    @java.lang.Override public com.amazaar.Protobuff.EntityPbOuterClass.StatusEnum getLifeTime() {
      @SuppressWarnings("deprecation")
      com.amazaar.Protobuff.EntityPbOuterClass.StatusEnum result = com.amazaar.Protobuff.EntityPbOuterClass.StatusEnum.valueOf(lifeTime_);
      return result == null ? com.amazaar.Protobuff.EntityPbOuterClass.StatusEnum.UNRECOGNIZED : result;
    }

    public static final int LOCALE_FIELD_NUMBER = 4;
    private com.amazaar.Protobuff.EntityPbOuterClass.LocalePb locale_;
    /**
     * <code>.com.amazaar.Protobuff.LocalePb locale = 4;</code>
     * @return Whether the locale field is set.
     */
    @java.lang.Override
    public boolean hasLocale() {
      return locale_ != null;
    }
    /**
     * <code>.com.amazaar.Protobuff.LocalePb locale = 4;</code>
     * @return The locale.
     */
    @java.lang.Override
    public com.amazaar.Protobuff.EntityPbOuterClass.LocalePb getLocale() {
      return locale_ == null ? com.amazaar.Protobuff.EntityPbOuterClass.LocalePb.getDefaultInstance() : locale_;
    }
    /**
     * <code>.com.amazaar.Protobuff.LocalePb locale = 4;</code>
     */
    @java.lang.Override
    public com.amazaar.Protobuff.EntityPbOuterClass.LocalePbOrBuilder getLocaleOrBuilder() {
      return getLocale();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (lifeTime_ != com.amazaar.Protobuff.EntityPbOuterClass.StatusEnum.UNKNOWN_STATUS.getNumber()) {
        output.writeEnum(3, lifeTime_);
      }
      if (locale_ != null) {
        output.writeMessage(4, getLocale());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (lifeTime_ != com.amazaar.Protobuff.EntityPbOuterClass.StatusEnum.UNKNOWN_STATUS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, lifeTime_);
      }
      if (locale_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getLocale());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.amazaar.Protobuff.EntityPbOuterClass.EntityPb)) {
        return super.equals(obj);
      }
      com.amazaar.Protobuff.EntityPbOuterClass.EntityPb other = (com.amazaar.Protobuff.EntityPbOuterClass.EntityPb) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (lifeTime_ != other.lifeTime_) return false;
      if (hasLocale() != other.hasLocale()) return false;
      if (hasLocale()) {
        if (!getLocale()
            .equals(other.getLocale())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + LIFETIME_FIELD_NUMBER;
      hash = (53 * hash) + lifeTime_;
      if (hasLocale()) {
        hash = (37 * hash) + LOCALE_FIELD_NUMBER;
        hash = (53 * hash) + getLocale().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.amazaar.Protobuff.EntityPbOuterClass.EntityPb parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.amazaar.Protobuff.EntityPbOuterClass.EntityPb parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.amazaar.Protobuff.EntityPbOuterClass.EntityPb parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.amazaar.Protobuff.EntityPbOuterClass.EntityPb parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.amazaar.Protobuff.EntityPbOuterClass.EntityPb parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.amazaar.Protobuff.EntityPbOuterClass.EntityPb parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.amazaar.Protobuff.EntityPbOuterClass.EntityPb parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.amazaar.Protobuff.EntityPbOuterClass.EntityPb parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.amazaar.Protobuff.EntityPbOuterClass.EntityPb parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.amazaar.Protobuff.EntityPbOuterClass.EntityPb parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.amazaar.Protobuff.EntityPbOuterClass.EntityPb parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.amazaar.Protobuff.EntityPbOuterClass.EntityPb parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.amazaar.Protobuff.EntityPbOuterClass.EntityPb prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.amazaar.Protobuff.EntityPb}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.amazaar.Protobuff.EntityPb)
        com.amazaar.Protobuff.EntityPbOuterClass.EntityPbOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.amazaar.Protobuff.EntityPbOuterClass.internal_static_com_amazaar_Protobuff_EntityPb_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.amazaar.Protobuff.EntityPbOuterClass.internal_static_com_amazaar_Protobuff_EntityPb_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.amazaar.Protobuff.EntityPbOuterClass.EntityPb.class, com.amazaar.Protobuff.EntityPbOuterClass.EntityPb.Builder.class);
      }

      // Construct using com.amazaar.Protobuff.EntityPbOuterClass.EntityPb.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        lifeTime_ = 0;

        if (localeBuilder_ == null) {
          locale_ = null;
        } else {
          locale_ = null;
          localeBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.amazaar.Protobuff.EntityPbOuterClass.internal_static_com_amazaar_Protobuff_EntityPb_descriptor;
      }

      @java.lang.Override
      public com.amazaar.Protobuff.EntityPbOuterClass.EntityPb getDefaultInstanceForType() {
        return com.amazaar.Protobuff.EntityPbOuterClass.EntityPb.getDefaultInstance();
      }

      @java.lang.Override
      public com.amazaar.Protobuff.EntityPbOuterClass.EntityPb build() {
        com.amazaar.Protobuff.EntityPbOuterClass.EntityPb result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.amazaar.Protobuff.EntityPbOuterClass.EntityPb buildPartial() {
        com.amazaar.Protobuff.EntityPbOuterClass.EntityPb result = new com.amazaar.Protobuff.EntityPbOuterClass.EntityPb(this);
        result.id_ = id_;
        result.lifeTime_ = lifeTime_;
        if (localeBuilder_ == null) {
          result.locale_ = locale_;
        } else {
          result.locale_ = localeBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.amazaar.Protobuff.EntityPbOuterClass.EntityPb) {
          return mergeFrom((com.amazaar.Protobuff.EntityPbOuterClass.EntityPb)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.amazaar.Protobuff.EntityPbOuterClass.EntityPb other) {
        if (other == com.amazaar.Protobuff.EntityPbOuterClass.EntityPb.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (other.lifeTime_ != 0) {
          setLifeTimeValue(other.getLifeTimeValue());
        }
        if (other.hasLocale()) {
          mergeLocale(other.getLocale());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.amazaar.Protobuff.EntityPbOuterClass.EntityPb parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.amazaar.Protobuff.EntityPbOuterClass.EntityPb) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private int lifeTime_ = 0;
      /**
       * <code>.com.amazaar.Protobuff.StatusEnum lifeTime = 3;</code>
       * @return The enum numeric value on the wire for lifeTime.
       */
      @java.lang.Override public int getLifeTimeValue() {
        return lifeTime_;
      }
      /**
       * <code>.com.amazaar.Protobuff.StatusEnum lifeTime = 3;</code>
       * @param value The enum numeric value on the wire for lifeTime to set.
       * @return This builder for chaining.
       */
      public Builder setLifeTimeValue(int value) {
        
        lifeTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.amazaar.Protobuff.StatusEnum lifeTime = 3;</code>
       * @return The lifeTime.
       */
      @java.lang.Override
      public com.amazaar.Protobuff.EntityPbOuterClass.StatusEnum getLifeTime() {
        @SuppressWarnings("deprecation")
        com.amazaar.Protobuff.EntityPbOuterClass.StatusEnum result = com.amazaar.Protobuff.EntityPbOuterClass.StatusEnum.valueOf(lifeTime_);
        return result == null ? com.amazaar.Protobuff.EntityPbOuterClass.StatusEnum.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.amazaar.Protobuff.StatusEnum lifeTime = 3;</code>
       * @param value The lifeTime to set.
       * @return This builder for chaining.
       */
      public Builder setLifeTime(com.amazaar.Protobuff.EntityPbOuterClass.StatusEnum value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        lifeTime_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.amazaar.Protobuff.StatusEnum lifeTime = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLifeTime() {
        
        lifeTime_ = 0;
        onChanged();
        return this;
      }

      private com.amazaar.Protobuff.EntityPbOuterClass.LocalePb locale_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.amazaar.Protobuff.EntityPbOuterClass.LocalePb, com.amazaar.Protobuff.EntityPbOuterClass.LocalePb.Builder, com.amazaar.Protobuff.EntityPbOuterClass.LocalePbOrBuilder> localeBuilder_;
      /**
       * <code>.com.amazaar.Protobuff.LocalePb locale = 4;</code>
       * @return Whether the locale field is set.
       */
      public boolean hasLocale() {
        return localeBuilder_ != null || locale_ != null;
      }
      /**
       * <code>.com.amazaar.Protobuff.LocalePb locale = 4;</code>
       * @return The locale.
       */
      public com.amazaar.Protobuff.EntityPbOuterClass.LocalePb getLocale() {
        if (localeBuilder_ == null) {
          return locale_ == null ? com.amazaar.Protobuff.EntityPbOuterClass.LocalePb.getDefaultInstance() : locale_;
        } else {
          return localeBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.amazaar.Protobuff.LocalePb locale = 4;</code>
       */
      public Builder setLocale(com.amazaar.Protobuff.EntityPbOuterClass.LocalePb value) {
        if (localeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          locale_ = value;
          onChanged();
        } else {
          localeBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.amazaar.Protobuff.LocalePb locale = 4;</code>
       */
      public Builder setLocale(
          com.amazaar.Protobuff.EntityPbOuterClass.LocalePb.Builder builderForValue) {
        if (localeBuilder_ == null) {
          locale_ = builderForValue.build();
          onChanged();
        } else {
          localeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.amazaar.Protobuff.LocalePb locale = 4;</code>
       */
      public Builder mergeLocale(com.amazaar.Protobuff.EntityPbOuterClass.LocalePb value) {
        if (localeBuilder_ == null) {
          if (locale_ != null) {
            locale_ =
              com.amazaar.Protobuff.EntityPbOuterClass.LocalePb.newBuilder(locale_).mergeFrom(value).buildPartial();
          } else {
            locale_ = value;
          }
          onChanged();
        } else {
          localeBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.amazaar.Protobuff.LocalePb locale = 4;</code>
       */
      public Builder clearLocale() {
        if (localeBuilder_ == null) {
          locale_ = null;
          onChanged();
        } else {
          locale_ = null;
          localeBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.amazaar.Protobuff.LocalePb locale = 4;</code>
       */
      public com.amazaar.Protobuff.EntityPbOuterClass.LocalePb.Builder getLocaleBuilder() {
        
        onChanged();
        return getLocaleFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.amazaar.Protobuff.LocalePb locale = 4;</code>
       */
      public com.amazaar.Protobuff.EntityPbOuterClass.LocalePbOrBuilder getLocaleOrBuilder() {
        if (localeBuilder_ != null) {
          return localeBuilder_.getMessageOrBuilder();
        } else {
          return locale_ == null ?
              com.amazaar.Protobuff.EntityPbOuterClass.LocalePb.getDefaultInstance() : locale_;
        }
      }
      /**
       * <code>.com.amazaar.Protobuff.LocalePb locale = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.amazaar.Protobuff.EntityPbOuterClass.LocalePb, com.amazaar.Protobuff.EntityPbOuterClass.LocalePb.Builder, com.amazaar.Protobuff.EntityPbOuterClass.LocalePbOrBuilder> 
          getLocaleFieldBuilder() {
        if (localeBuilder_ == null) {
          localeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.amazaar.Protobuff.EntityPbOuterClass.LocalePb, com.amazaar.Protobuff.EntityPbOuterClass.LocalePb.Builder, com.amazaar.Protobuff.EntityPbOuterClass.LocalePbOrBuilder>(
                  getLocale(),
                  getParentForChildren(),
                  isClean());
          locale_ = null;
        }
        return localeBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.amazaar.Protobuff.EntityPb)
    }

    // @@protoc_insertion_point(class_scope:com.amazaar.Protobuff.EntityPb)
    private static final com.amazaar.Protobuff.EntityPbOuterClass.EntityPb DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.amazaar.Protobuff.EntityPbOuterClass.EntityPb();
    }

    public static com.amazaar.Protobuff.EntityPbOuterClass.EntityPb getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EntityPb>
        PARSER = new com.google.protobuf.AbstractParser<EntityPb>() {
      @java.lang.Override
      public EntityPb parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EntityPb(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EntityPb> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EntityPb> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.amazaar.Protobuff.EntityPbOuterClass.EntityPb getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LocalePbOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.amazaar.Protobuff.LocalePb)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.amazaar.Protobuff.TimeZoneEnum defaultTimeZone = 1;</code>
     * @return The enum numeric value on the wire for defaultTimeZone.
     */
    int getDefaultTimeZoneValue();
    /**
     * <code>.com.amazaar.Protobuff.TimeZoneEnum defaultTimeZone = 1;</code>
     * @return The defaultTimeZone.
     */
    com.amazaar.Protobuff.TimePbOuterClass.TimeZoneEnum getDefaultTimeZone();
  }
  /**
   * Protobuf type {@code com.amazaar.Protobuff.LocalePb}
   */
  public static final class LocalePb extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.amazaar.Protobuff.LocalePb)
      LocalePbOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LocalePb.newBuilder() to construct.
    private LocalePb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LocalePb() {
      defaultTimeZone_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LocalePb();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LocalePb(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              defaultTimeZone_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.amazaar.Protobuff.EntityPbOuterClass.internal_static_com_amazaar_Protobuff_LocalePb_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.amazaar.Protobuff.EntityPbOuterClass.internal_static_com_amazaar_Protobuff_LocalePb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.amazaar.Protobuff.EntityPbOuterClass.LocalePb.class, com.amazaar.Protobuff.EntityPbOuterClass.LocalePb.Builder.class);
    }

    public static final int DEFAULTTIMEZONE_FIELD_NUMBER = 1;
    private int defaultTimeZone_;
    /**
     * <code>.com.amazaar.Protobuff.TimeZoneEnum defaultTimeZone = 1;</code>
     * @return The enum numeric value on the wire for defaultTimeZone.
     */
    @java.lang.Override public int getDefaultTimeZoneValue() {
      return defaultTimeZone_;
    }
    /**
     * <code>.com.amazaar.Protobuff.TimeZoneEnum defaultTimeZone = 1;</code>
     * @return The defaultTimeZone.
     */
    @java.lang.Override public com.amazaar.Protobuff.TimePbOuterClass.TimeZoneEnum getDefaultTimeZone() {
      @SuppressWarnings("deprecation")
      com.amazaar.Protobuff.TimePbOuterClass.TimeZoneEnum result = com.amazaar.Protobuff.TimePbOuterClass.TimeZoneEnum.valueOf(defaultTimeZone_);
      return result == null ? com.amazaar.Protobuff.TimePbOuterClass.TimeZoneEnum.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (defaultTimeZone_ != com.amazaar.Protobuff.TimePbOuterClass.TimeZoneEnum.UNKNOWN_TIME_ZONE.getNumber()) {
        output.writeEnum(1, defaultTimeZone_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (defaultTimeZone_ != com.amazaar.Protobuff.TimePbOuterClass.TimeZoneEnum.UNKNOWN_TIME_ZONE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, defaultTimeZone_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.amazaar.Protobuff.EntityPbOuterClass.LocalePb)) {
        return super.equals(obj);
      }
      com.amazaar.Protobuff.EntityPbOuterClass.LocalePb other = (com.amazaar.Protobuff.EntityPbOuterClass.LocalePb) obj;

      if (defaultTimeZone_ != other.defaultTimeZone_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DEFAULTTIMEZONE_FIELD_NUMBER;
      hash = (53 * hash) + defaultTimeZone_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.amazaar.Protobuff.EntityPbOuterClass.LocalePb parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.amazaar.Protobuff.EntityPbOuterClass.LocalePb parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.amazaar.Protobuff.EntityPbOuterClass.LocalePb parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.amazaar.Protobuff.EntityPbOuterClass.LocalePb parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.amazaar.Protobuff.EntityPbOuterClass.LocalePb parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.amazaar.Protobuff.EntityPbOuterClass.LocalePb parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.amazaar.Protobuff.EntityPbOuterClass.LocalePb parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.amazaar.Protobuff.EntityPbOuterClass.LocalePb parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.amazaar.Protobuff.EntityPbOuterClass.LocalePb parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.amazaar.Protobuff.EntityPbOuterClass.LocalePb parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.amazaar.Protobuff.EntityPbOuterClass.LocalePb parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.amazaar.Protobuff.EntityPbOuterClass.LocalePb parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.amazaar.Protobuff.EntityPbOuterClass.LocalePb prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.amazaar.Protobuff.LocalePb}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.amazaar.Protobuff.LocalePb)
        com.amazaar.Protobuff.EntityPbOuterClass.LocalePbOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.amazaar.Protobuff.EntityPbOuterClass.internal_static_com_amazaar_Protobuff_LocalePb_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.amazaar.Protobuff.EntityPbOuterClass.internal_static_com_amazaar_Protobuff_LocalePb_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.amazaar.Protobuff.EntityPbOuterClass.LocalePb.class, com.amazaar.Protobuff.EntityPbOuterClass.LocalePb.Builder.class);
      }

      // Construct using com.amazaar.Protobuff.EntityPbOuterClass.LocalePb.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        defaultTimeZone_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.amazaar.Protobuff.EntityPbOuterClass.internal_static_com_amazaar_Protobuff_LocalePb_descriptor;
      }

      @java.lang.Override
      public com.amazaar.Protobuff.EntityPbOuterClass.LocalePb getDefaultInstanceForType() {
        return com.amazaar.Protobuff.EntityPbOuterClass.LocalePb.getDefaultInstance();
      }

      @java.lang.Override
      public com.amazaar.Protobuff.EntityPbOuterClass.LocalePb build() {
        com.amazaar.Protobuff.EntityPbOuterClass.LocalePb result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.amazaar.Protobuff.EntityPbOuterClass.LocalePb buildPartial() {
        com.amazaar.Protobuff.EntityPbOuterClass.LocalePb result = new com.amazaar.Protobuff.EntityPbOuterClass.LocalePb(this);
        result.defaultTimeZone_ = defaultTimeZone_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.amazaar.Protobuff.EntityPbOuterClass.LocalePb) {
          return mergeFrom((com.amazaar.Protobuff.EntityPbOuterClass.LocalePb)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.amazaar.Protobuff.EntityPbOuterClass.LocalePb other) {
        if (other == com.amazaar.Protobuff.EntityPbOuterClass.LocalePb.getDefaultInstance()) return this;
        if (other.defaultTimeZone_ != 0) {
          setDefaultTimeZoneValue(other.getDefaultTimeZoneValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.amazaar.Protobuff.EntityPbOuterClass.LocalePb parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.amazaar.Protobuff.EntityPbOuterClass.LocalePb) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int defaultTimeZone_ = 0;
      /**
       * <code>.com.amazaar.Protobuff.TimeZoneEnum defaultTimeZone = 1;</code>
       * @return The enum numeric value on the wire for defaultTimeZone.
       */
      @java.lang.Override public int getDefaultTimeZoneValue() {
        return defaultTimeZone_;
      }
      /**
       * <code>.com.amazaar.Protobuff.TimeZoneEnum defaultTimeZone = 1;</code>
       * @param value The enum numeric value on the wire for defaultTimeZone to set.
       * @return This builder for chaining.
       */
      public Builder setDefaultTimeZoneValue(int value) {
        
        defaultTimeZone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.amazaar.Protobuff.TimeZoneEnum defaultTimeZone = 1;</code>
       * @return The defaultTimeZone.
       */
      @java.lang.Override
      public com.amazaar.Protobuff.TimePbOuterClass.TimeZoneEnum getDefaultTimeZone() {
        @SuppressWarnings("deprecation")
        com.amazaar.Protobuff.TimePbOuterClass.TimeZoneEnum result = com.amazaar.Protobuff.TimePbOuterClass.TimeZoneEnum.valueOf(defaultTimeZone_);
        return result == null ? com.amazaar.Protobuff.TimePbOuterClass.TimeZoneEnum.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.amazaar.Protobuff.TimeZoneEnum defaultTimeZone = 1;</code>
       * @param value The defaultTimeZone to set.
       * @return This builder for chaining.
       */
      public Builder setDefaultTimeZone(com.amazaar.Protobuff.TimePbOuterClass.TimeZoneEnum value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        defaultTimeZone_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.amazaar.Protobuff.TimeZoneEnum defaultTimeZone = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDefaultTimeZone() {
        
        defaultTimeZone_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.amazaar.Protobuff.LocalePb)
    }

    // @@protoc_insertion_point(class_scope:com.amazaar.Protobuff.LocalePb)
    private static final com.amazaar.Protobuff.EntityPbOuterClass.LocalePb DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.amazaar.Protobuff.EntityPbOuterClass.LocalePb();
    }

    public static com.amazaar.Protobuff.EntityPbOuterClass.LocalePb getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LocalePb>
        PARSER = new com.google.protobuf.AbstractParser<LocalePb>() {
      @java.lang.Override
      public LocalePb parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LocalePb(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LocalePb> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LocalePb> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.amazaar.Protobuff.EntityPbOuterClass.LocalePb getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_amazaar_Protobuff_EntityPb_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_amazaar_Protobuff_EntityPb_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_amazaar_Protobuff_LocalePb_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_amazaar_Protobuff_LocalePb_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016entityPb.proto\022\025com.amazaar.Protobuff\032" +
      "\014timePb.proto\"|\n\010EntityPb\022\n\n\002id\030\001 \001(\t\0223\n" +
      "\010lifeTime\030\003 \001(\0162!.com.amazaar.Protobuff." +
      "StatusEnum\022/\n\006locale\030\004 \001(\0132\037.com.amazaar" +
      ".Protobuff.LocalePb\"H\n\010LocalePb\022<\n\017defau" +
      "ltTimeZone\030\001 \001(\0162#.com.amazaar.Protobuff" +
      ".TimeZoneEnum*U\n\nStatusEnum\022\022\n\016UNKNOWN_S" +
      "TATUS\020\000\022\n\n\006ACTIVE\020\001\022\013\n\007DELETED\020\002\022\r\n\tSUSP" +
      "UNDED\020\003\022\013\n\007BLOCKED\020\004b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.amazaar.Protobuff.TimePbOuterClass.getDescriptor(),
        });
    internal_static_com_amazaar_Protobuff_EntityPb_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_amazaar_Protobuff_EntityPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_amazaar_Protobuff_EntityPb_descriptor,
        new java.lang.String[] { "Id", "LifeTime", "Locale", });
    internal_static_com_amazaar_Protobuff_LocalePb_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_amazaar_Protobuff_LocalePb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_amazaar_Protobuff_LocalePb_descriptor,
        new java.lang.String[] { "DefaultTimeZone", });
    com.amazaar.Protobuff.TimePbOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
