// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: paymentPb.proto

package com.amazaar.Protobuff;

public final class PaymentPbOuterClass {
  private PaymentPbOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.amazaar.Protobuff.PaymentStatusEnum}
   */
  public enum PaymentStatusEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN_PAYMENT_STATUS = 0;</code>
     */
    UNKNOWN_PAYMENT_STATUS(0),
    /**
     * <code>SUCCESS = 1;</code>
     */
    SUCCESS(1),
    /**
     * <code>FAILED = 2;</code>
     */
    FAILED(2),
    /**
     * <code>WAITING = 3;</code>
     */
    WAITING(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN_PAYMENT_STATUS = 0;</code>
     */
    public static final int UNKNOWN_PAYMENT_STATUS_VALUE = 0;
    /**
     * <code>SUCCESS = 1;</code>
     */
    public static final int SUCCESS_VALUE = 1;
    /**
     * <code>FAILED = 2;</code>
     */
    public static final int FAILED_VALUE = 2;
    /**
     * <code>WAITING = 3;</code>
     */
    public static final int WAITING_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PaymentStatusEnum valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static PaymentStatusEnum forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN_PAYMENT_STATUS;
        case 1: return SUCCESS;
        case 2: return FAILED;
        case 3: return WAITING;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PaymentStatusEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PaymentStatusEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PaymentStatusEnum>() {
            public PaymentStatusEnum findValueByNumber(int number) {
              return PaymentStatusEnum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.amazaar.Protobuff.PaymentPbOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final PaymentStatusEnum[] VALUES = values();

    public static PaymentStatusEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private PaymentStatusEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.amazaar.Protobuff.PaymentStatusEnum)
  }

  /**
   * Protobuf enum {@code com.amazaar.Protobuff.PaymentModeEnum}
   */
  public enum PaymentModeEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN_MODE = 0;</code>
     */
    UNKNOWN_MODE(0),
    /**
     * <code>GOOGLE_PAY = 1;</code>
     */
    GOOGLE_PAY(1),
    /**
     * <code>CASH_ON_DELIVERY = 2;</code>
     */
    CASH_ON_DELIVERY(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN_MODE = 0;</code>
     */
    public static final int UNKNOWN_MODE_VALUE = 0;
    /**
     * <code>GOOGLE_PAY = 1;</code>
     */
    public static final int GOOGLE_PAY_VALUE = 1;
    /**
     * <code>CASH_ON_DELIVERY = 2;</code>
     */
    public static final int CASH_ON_DELIVERY_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PaymentModeEnum valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static PaymentModeEnum forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN_MODE;
        case 1: return GOOGLE_PAY;
        case 2: return CASH_ON_DELIVERY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PaymentModeEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PaymentModeEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PaymentModeEnum>() {
            public PaymentModeEnum findValueByNumber(int number) {
              return PaymentModeEnum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.amazaar.Protobuff.PaymentPbOuterClass.getDescriptor().getEnumTypes().get(1);
    }

    private static final PaymentModeEnum[] VALUES = values();

    public static PaymentModeEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private PaymentModeEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.amazaar.Protobuff.PaymentModeEnum)
  }

  public interface PaymentPbOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.amazaar.Protobuff.PaymentPb)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string txnId = 1;</code>
     * @return The txnId.
     */
    java.lang.String getTxnId();
    /**
     * <code>string txnId = 1;</code>
     * @return The bytes for txnId.
     */
    com.google.protobuf.ByteString
        getTxnIdBytes();

    /**
     * <code>string responseCode = 2;</code>
     * @return The responseCode.
     */
    java.lang.String getResponseCode();
    /**
     * <code>string responseCode = 2;</code>
     * @return The bytes for responseCode.
     */
    com.google.protobuf.ByteString
        getResponseCodeBytes();

    /**
     * <code>.com.amazaar.Protobuff.PaymentStatusEnum status = 3;</code>
     * @return The enum numeric value on the wire for status.
     */
    int getStatusValue();
    /**
     * <code>.com.amazaar.Protobuff.PaymentStatusEnum status = 3;</code>
     * @return The status.
     */
    com.amazaar.Protobuff.PaymentPbOuterClass.PaymentStatusEnum getStatus();

    /**
     * <code>string txnRef = 4;</code>
     * @return The txnRef.
     */
    java.lang.String getTxnRef();
    /**
     * <code>string txnRef = 4;</code>
     * @return The bytes for txnRef.
     */
    com.google.protobuf.ByteString
        getTxnRefBytes();

    /**
     * <code>.com.amazaar.Protobuff.CustomerPbRef customerRef = 5;</code>
     * @return Whether the customerRef field is set.
     */
    boolean hasCustomerRef();
    /**
     * <code>.com.amazaar.Protobuff.CustomerPbRef customerRef = 5;</code>
     * @return The customerRef.
     */
    com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPbRef getCustomerRef();
    /**
     * <code>.com.amazaar.Protobuff.CustomerPbRef customerRef = 5;</code>
     */
    com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPbRefOrBuilder getCustomerRefOrBuilder();

    /**
     * <code>.com.amazaar.Protobuff.TimePb time = 6;</code>
     * @return Whether the time field is set.
     */
    boolean hasTime();
    /**
     * <code>.com.amazaar.Protobuff.TimePb time = 6;</code>
     * @return The time.
     */
    com.amazaar.Protobuff.TimePbOuterClass.TimePb getTime();
    /**
     * <code>.com.amazaar.Protobuff.TimePb time = 6;</code>
     */
    com.amazaar.Protobuff.TimePbOuterClass.TimePbOrBuilder getTimeOrBuilder();
  }
  /**
   * Protobuf type {@code com.amazaar.Protobuff.PaymentPb}
   */
  public static final class PaymentPb extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.amazaar.Protobuff.PaymentPb)
      PaymentPbOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PaymentPb.newBuilder() to construct.
    private PaymentPb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PaymentPb() {
      txnId_ = "";
      responseCode_ = "";
      status_ = 0;
      txnRef_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PaymentPb();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PaymentPb(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              txnId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              responseCode_ = s;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              txnRef_ = s;
              break;
            }
            case 42: {
              com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPbRef.Builder subBuilder = null;
              if (customerRef_ != null) {
                subBuilder = customerRef_.toBuilder();
              }
              customerRef_ = input.readMessage(com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPbRef.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(customerRef_);
                customerRef_ = subBuilder.buildPartial();
              }

              break;
            }
            case 50: {
              com.amazaar.Protobuff.TimePbOuterClass.TimePb.Builder subBuilder = null;
              if (time_ != null) {
                subBuilder = time_.toBuilder();
              }
              time_ = input.readMessage(com.amazaar.Protobuff.TimePbOuterClass.TimePb.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(time_);
                time_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.amazaar.Protobuff.PaymentPbOuterClass.internal_static_com_amazaar_Protobuff_PaymentPb_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.amazaar.Protobuff.PaymentPbOuterClass.internal_static_com_amazaar_Protobuff_PaymentPb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.amazaar.Protobuff.PaymentPbOuterClass.PaymentPb.class, com.amazaar.Protobuff.PaymentPbOuterClass.PaymentPb.Builder.class);
    }

    public static final int TXNID_FIELD_NUMBER = 1;
    private volatile java.lang.Object txnId_;
    /**
     * <code>string txnId = 1;</code>
     * @return The txnId.
     */
    @java.lang.Override
    public java.lang.String getTxnId() {
      java.lang.Object ref = txnId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        txnId_ = s;
        return s;
      }
    }
    /**
     * <code>string txnId = 1;</code>
     * @return The bytes for txnId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTxnIdBytes() {
      java.lang.Object ref = txnId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        txnId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESPONSECODE_FIELD_NUMBER = 2;
    private volatile java.lang.Object responseCode_;
    /**
     * <code>string responseCode = 2;</code>
     * @return The responseCode.
     */
    @java.lang.Override
    public java.lang.String getResponseCode() {
      java.lang.Object ref = responseCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        responseCode_ = s;
        return s;
      }
    }
    /**
     * <code>string responseCode = 2;</code>
     * @return The bytes for responseCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getResponseCodeBytes() {
      java.lang.Object ref = responseCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        responseCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 3;
    private int status_;
    /**
     * <code>.com.amazaar.Protobuff.PaymentStatusEnum status = 3;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.com.amazaar.Protobuff.PaymentStatusEnum status = 3;</code>
     * @return The status.
     */
    @java.lang.Override public com.amazaar.Protobuff.PaymentPbOuterClass.PaymentStatusEnum getStatus() {
      @SuppressWarnings("deprecation")
      com.amazaar.Protobuff.PaymentPbOuterClass.PaymentStatusEnum result = com.amazaar.Protobuff.PaymentPbOuterClass.PaymentStatusEnum.valueOf(status_);
      return result == null ? com.amazaar.Protobuff.PaymentPbOuterClass.PaymentStatusEnum.UNRECOGNIZED : result;
    }

    public static final int TXNREF_FIELD_NUMBER = 4;
    private volatile java.lang.Object txnRef_;
    /**
     * <code>string txnRef = 4;</code>
     * @return The txnRef.
     */
    @java.lang.Override
    public java.lang.String getTxnRef() {
      java.lang.Object ref = txnRef_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        txnRef_ = s;
        return s;
      }
    }
    /**
     * <code>string txnRef = 4;</code>
     * @return The bytes for txnRef.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTxnRefBytes() {
      java.lang.Object ref = txnRef_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        txnRef_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CUSTOMERREF_FIELD_NUMBER = 5;
    private com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPbRef customerRef_;
    /**
     * <code>.com.amazaar.Protobuff.CustomerPbRef customerRef = 5;</code>
     * @return Whether the customerRef field is set.
     */
    @java.lang.Override
    public boolean hasCustomerRef() {
      return customerRef_ != null;
    }
    /**
     * <code>.com.amazaar.Protobuff.CustomerPbRef customerRef = 5;</code>
     * @return The customerRef.
     */
    @java.lang.Override
    public com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPbRef getCustomerRef() {
      return customerRef_ == null ? com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPbRef.getDefaultInstance() : customerRef_;
    }
    /**
     * <code>.com.amazaar.Protobuff.CustomerPbRef customerRef = 5;</code>
     */
    @java.lang.Override
    public com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPbRefOrBuilder getCustomerRefOrBuilder() {
      return getCustomerRef();
    }

    public static final int TIME_FIELD_NUMBER = 6;
    private com.amazaar.Protobuff.TimePbOuterClass.TimePb time_;
    /**
     * <code>.com.amazaar.Protobuff.TimePb time = 6;</code>
     * @return Whether the time field is set.
     */
    @java.lang.Override
    public boolean hasTime() {
      return time_ != null;
    }
    /**
     * <code>.com.amazaar.Protobuff.TimePb time = 6;</code>
     * @return The time.
     */
    @java.lang.Override
    public com.amazaar.Protobuff.TimePbOuterClass.TimePb getTime() {
      return time_ == null ? com.amazaar.Protobuff.TimePbOuterClass.TimePb.getDefaultInstance() : time_;
    }
    /**
     * <code>.com.amazaar.Protobuff.TimePb time = 6;</code>
     */
    @java.lang.Override
    public com.amazaar.Protobuff.TimePbOuterClass.TimePbOrBuilder getTimeOrBuilder() {
      return getTime();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTxnIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, txnId_);
      }
      if (!getResponseCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, responseCode_);
      }
      if (status_ != com.amazaar.Protobuff.PaymentPbOuterClass.PaymentStatusEnum.UNKNOWN_PAYMENT_STATUS.getNumber()) {
        output.writeEnum(3, status_);
      }
      if (!getTxnRefBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, txnRef_);
      }
      if (customerRef_ != null) {
        output.writeMessage(5, getCustomerRef());
      }
      if (time_ != null) {
        output.writeMessage(6, getTime());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTxnIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, txnId_);
      }
      if (!getResponseCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, responseCode_);
      }
      if (status_ != com.amazaar.Protobuff.PaymentPbOuterClass.PaymentStatusEnum.UNKNOWN_PAYMENT_STATUS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, status_);
      }
      if (!getTxnRefBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, txnRef_);
      }
      if (customerRef_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getCustomerRef());
      }
      if (time_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getTime());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.amazaar.Protobuff.PaymentPbOuterClass.PaymentPb)) {
        return super.equals(obj);
      }
      com.amazaar.Protobuff.PaymentPbOuterClass.PaymentPb other = (com.amazaar.Protobuff.PaymentPbOuterClass.PaymentPb) obj;

      if (!getTxnId()
          .equals(other.getTxnId())) return false;
      if (!getResponseCode()
          .equals(other.getResponseCode())) return false;
      if (status_ != other.status_) return false;
      if (!getTxnRef()
          .equals(other.getTxnRef())) return false;
      if (hasCustomerRef() != other.hasCustomerRef()) return false;
      if (hasCustomerRef()) {
        if (!getCustomerRef()
            .equals(other.getCustomerRef())) return false;
      }
      if (hasTime() != other.hasTime()) return false;
      if (hasTime()) {
        if (!getTime()
            .equals(other.getTime())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TXNID_FIELD_NUMBER;
      hash = (53 * hash) + getTxnId().hashCode();
      hash = (37 * hash) + RESPONSECODE_FIELD_NUMBER;
      hash = (53 * hash) + getResponseCode().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      hash = (37 * hash) + TXNREF_FIELD_NUMBER;
      hash = (53 * hash) + getTxnRef().hashCode();
      if (hasCustomerRef()) {
        hash = (37 * hash) + CUSTOMERREF_FIELD_NUMBER;
        hash = (53 * hash) + getCustomerRef().hashCode();
      }
      if (hasTime()) {
        hash = (37 * hash) + TIME_FIELD_NUMBER;
        hash = (53 * hash) + getTime().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.amazaar.Protobuff.PaymentPbOuterClass.PaymentPb parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.amazaar.Protobuff.PaymentPbOuterClass.PaymentPb parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.amazaar.Protobuff.PaymentPbOuterClass.PaymentPb parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.amazaar.Protobuff.PaymentPbOuterClass.PaymentPb parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.amazaar.Protobuff.PaymentPbOuterClass.PaymentPb parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.amazaar.Protobuff.PaymentPbOuterClass.PaymentPb parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.amazaar.Protobuff.PaymentPbOuterClass.PaymentPb parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.amazaar.Protobuff.PaymentPbOuterClass.PaymentPb parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.amazaar.Protobuff.PaymentPbOuterClass.PaymentPb parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.amazaar.Protobuff.PaymentPbOuterClass.PaymentPb parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.amazaar.Protobuff.PaymentPbOuterClass.PaymentPb parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.amazaar.Protobuff.PaymentPbOuterClass.PaymentPb parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.amazaar.Protobuff.PaymentPbOuterClass.PaymentPb prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.amazaar.Protobuff.PaymentPb}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.amazaar.Protobuff.PaymentPb)
        com.amazaar.Protobuff.PaymentPbOuterClass.PaymentPbOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.amazaar.Protobuff.PaymentPbOuterClass.internal_static_com_amazaar_Protobuff_PaymentPb_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.amazaar.Protobuff.PaymentPbOuterClass.internal_static_com_amazaar_Protobuff_PaymentPb_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.amazaar.Protobuff.PaymentPbOuterClass.PaymentPb.class, com.amazaar.Protobuff.PaymentPbOuterClass.PaymentPb.Builder.class);
      }

      // Construct using com.amazaar.Protobuff.PaymentPbOuterClass.PaymentPb.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        txnId_ = "";

        responseCode_ = "";

        status_ = 0;

        txnRef_ = "";

        if (customerRefBuilder_ == null) {
          customerRef_ = null;
        } else {
          customerRef_ = null;
          customerRefBuilder_ = null;
        }
        if (timeBuilder_ == null) {
          time_ = null;
        } else {
          time_ = null;
          timeBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.amazaar.Protobuff.PaymentPbOuterClass.internal_static_com_amazaar_Protobuff_PaymentPb_descriptor;
      }

      @java.lang.Override
      public com.amazaar.Protobuff.PaymentPbOuterClass.PaymentPb getDefaultInstanceForType() {
        return com.amazaar.Protobuff.PaymentPbOuterClass.PaymentPb.getDefaultInstance();
      }

      @java.lang.Override
      public com.amazaar.Protobuff.PaymentPbOuterClass.PaymentPb build() {
        com.amazaar.Protobuff.PaymentPbOuterClass.PaymentPb result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.amazaar.Protobuff.PaymentPbOuterClass.PaymentPb buildPartial() {
        com.amazaar.Protobuff.PaymentPbOuterClass.PaymentPb result = new com.amazaar.Protobuff.PaymentPbOuterClass.PaymentPb(this);
        result.txnId_ = txnId_;
        result.responseCode_ = responseCode_;
        result.status_ = status_;
        result.txnRef_ = txnRef_;
        if (customerRefBuilder_ == null) {
          result.customerRef_ = customerRef_;
        } else {
          result.customerRef_ = customerRefBuilder_.build();
        }
        if (timeBuilder_ == null) {
          result.time_ = time_;
        } else {
          result.time_ = timeBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.amazaar.Protobuff.PaymentPbOuterClass.PaymentPb) {
          return mergeFrom((com.amazaar.Protobuff.PaymentPbOuterClass.PaymentPb)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.amazaar.Protobuff.PaymentPbOuterClass.PaymentPb other) {
        if (other == com.amazaar.Protobuff.PaymentPbOuterClass.PaymentPb.getDefaultInstance()) return this;
        if (!other.getTxnId().isEmpty()) {
          txnId_ = other.txnId_;
          onChanged();
        }
        if (!other.getResponseCode().isEmpty()) {
          responseCode_ = other.responseCode_;
          onChanged();
        }
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        if (!other.getTxnRef().isEmpty()) {
          txnRef_ = other.txnRef_;
          onChanged();
        }
        if (other.hasCustomerRef()) {
          mergeCustomerRef(other.getCustomerRef());
        }
        if (other.hasTime()) {
          mergeTime(other.getTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.amazaar.Protobuff.PaymentPbOuterClass.PaymentPb parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.amazaar.Protobuff.PaymentPbOuterClass.PaymentPb) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object txnId_ = "";
      /**
       * <code>string txnId = 1;</code>
       * @return The txnId.
       */
      public java.lang.String getTxnId() {
        java.lang.Object ref = txnId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          txnId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string txnId = 1;</code>
       * @return The bytes for txnId.
       */
      public com.google.protobuf.ByteString
          getTxnIdBytes() {
        java.lang.Object ref = txnId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          txnId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string txnId = 1;</code>
       * @param value The txnId to set.
       * @return This builder for chaining.
       */
      public Builder setTxnId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        txnId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string txnId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTxnId() {
        
        txnId_ = getDefaultInstance().getTxnId();
        onChanged();
        return this;
      }
      /**
       * <code>string txnId = 1;</code>
       * @param value The bytes for txnId to set.
       * @return This builder for chaining.
       */
      public Builder setTxnIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        txnId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object responseCode_ = "";
      /**
       * <code>string responseCode = 2;</code>
       * @return The responseCode.
       */
      public java.lang.String getResponseCode() {
        java.lang.Object ref = responseCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          responseCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string responseCode = 2;</code>
       * @return The bytes for responseCode.
       */
      public com.google.protobuf.ByteString
          getResponseCodeBytes() {
        java.lang.Object ref = responseCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          responseCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string responseCode = 2;</code>
       * @param value The responseCode to set.
       * @return This builder for chaining.
       */
      public Builder setResponseCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        responseCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string responseCode = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearResponseCode() {
        
        responseCode_ = getDefaultInstance().getResponseCode();
        onChanged();
        return this;
      }
      /**
       * <code>string responseCode = 2;</code>
       * @param value The bytes for responseCode to set.
       * @return This builder for chaining.
       */
      public Builder setResponseCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        responseCode_ = value;
        onChanged();
        return this;
      }

      private int status_ = 0;
      /**
       * <code>.com.amazaar.Protobuff.PaymentStatusEnum status = 3;</code>
       * @return The enum numeric value on the wire for status.
       */
      @java.lang.Override public int getStatusValue() {
        return status_;
      }
      /**
       * <code>.com.amazaar.Protobuff.PaymentStatusEnum status = 3;</code>
       * @param value The enum numeric value on the wire for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusValue(int value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.amazaar.Protobuff.PaymentStatusEnum status = 3;</code>
       * @return The status.
       */
      @java.lang.Override
      public com.amazaar.Protobuff.PaymentPbOuterClass.PaymentStatusEnum getStatus() {
        @SuppressWarnings("deprecation")
        com.amazaar.Protobuff.PaymentPbOuterClass.PaymentStatusEnum result = com.amazaar.Protobuff.PaymentPbOuterClass.PaymentStatusEnum.valueOf(status_);
        return result == null ? com.amazaar.Protobuff.PaymentPbOuterClass.PaymentStatusEnum.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.amazaar.Protobuff.PaymentStatusEnum status = 3;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(com.amazaar.Protobuff.PaymentPbOuterClass.PaymentStatusEnum value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.amazaar.Protobuff.PaymentStatusEnum status = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object txnRef_ = "";
      /**
       * <code>string txnRef = 4;</code>
       * @return The txnRef.
       */
      public java.lang.String getTxnRef() {
        java.lang.Object ref = txnRef_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          txnRef_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string txnRef = 4;</code>
       * @return The bytes for txnRef.
       */
      public com.google.protobuf.ByteString
          getTxnRefBytes() {
        java.lang.Object ref = txnRef_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          txnRef_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string txnRef = 4;</code>
       * @param value The txnRef to set.
       * @return This builder for chaining.
       */
      public Builder setTxnRef(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        txnRef_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string txnRef = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTxnRef() {
        
        txnRef_ = getDefaultInstance().getTxnRef();
        onChanged();
        return this;
      }
      /**
       * <code>string txnRef = 4;</code>
       * @param value The bytes for txnRef to set.
       * @return This builder for chaining.
       */
      public Builder setTxnRefBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        txnRef_ = value;
        onChanged();
        return this;
      }

      private com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPbRef customerRef_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPbRef, com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPbRef.Builder, com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPbRefOrBuilder> customerRefBuilder_;
      /**
       * <code>.com.amazaar.Protobuff.CustomerPbRef customerRef = 5;</code>
       * @return Whether the customerRef field is set.
       */
      public boolean hasCustomerRef() {
        return customerRefBuilder_ != null || customerRef_ != null;
      }
      /**
       * <code>.com.amazaar.Protobuff.CustomerPbRef customerRef = 5;</code>
       * @return The customerRef.
       */
      public com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPbRef getCustomerRef() {
        if (customerRefBuilder_ == null) {
          return customerRef_ == null ? com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPbRef.getDefaultInstance() : customerRef_;
        } else {
          return customerRefBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.amazaar.Protobuff.CustomerPbRef customerRef = 5;</code>
       */
      public Builder setCustomerRef(com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPbRef value) {
        if (customerRefBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          customerRef_ = value;
          onChanged();
        } else {
          customerRefBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.amazaar.Protobuff.CustomerPbRef customerRef = 5;</code>
       */
      public Builder setCustomerRef(
          com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPbRef.Builder builderForValue) {
        if (customerRefBuilder_ == null) {
          customerRef_ = builderForValue.build();
          onChanged();
        } else {
          customerRefBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.amazaar.Protobuff.CustomerPbRef customerRef = 5;</code>
       */
      public Builder mergeCustomerRef(com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPbRef value) {
        if (customerRefBuilder_ == null) {
          if (customerRef_ != null) {
            customerRef_ =
              com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPbRef.newBuilder(customerRef_).mergeFrom(value).buildPartial();
          } else {
            customerRef_ = value;
          }
          onChanged();
        } else {
          customerRefBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.amazaar.Protobuff.CustomerPbRef customerRef = 5;</code>
       */
      public Builder clearCustomerRef() {
        if (customerRefBuilder_ == null) {
          customerRef_ = null;
          onChanged();
        } else {
          customerRef_ = null;
          customerRefBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.amazaar.Protobuff.CustomerPbRef customerRef = 5;</code>
       */
      public com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPbRef.Builder getCustomerRefBuilder() {
        
        onChanged();
        return getCustomerRefFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.amazaar.Protobuff.CustomerPbRef customerRef = 5;</code>
       */
      public com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPbRefOrBuilder getCustomerRefOrBuilder() {
        if (customerRefBuilder_ != null) {
          return customerRefBuilder_.getMessageOrBuilder();
        } else {
          return customerRef_ == null ?
              com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPbRef.getDefaultInstance() : customerRef_;
        }
      }
      /**
       * <code>.com.amazaar.Protobuff.CustomerPbRef customerRef = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPbRef, com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPbRef.Builder, com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPbRefOrBuilder> 
          getCustomerRefFieldBuilder() {
        if (customerRefBuilder_ == null) {
          customerRefBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPbRef, com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPbRef.Builder, com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPbRefOrBuilder>(
                  getCustomerRef(),
                  getParentForChildren(),
                  isClean());
          customerRef_ = null;
        }
        return customerRefBuilder_;
      }

      private com.amazaar.Protobuff.TimePbOuterClass.TimePb time_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.amazaar.Protobuff.TimePbOuterClass.TimePb, com.amazaar.Protobuff.TimePbOuterClass.TimePb.Builder, com.amazaar.Protobuff.TimePbOuterClass.TimePbOrBuilder> timeBuilder_;
      /**
       * <code>.com.amazaar.Protobuff.TimePb time = 6;</code>
       * @return Whether the time field is set.
       */
      public boolean hasTime() {
        return timeBuilder_ != null || time_ != null;
      }
      /**
       * <code>.com.amazaar.Protobuff.TimePb time = 6;</code>
       * @return The time.
       */
      public com.amazaar.Protobuff.TimePbOuterClass.TimePb getTime() {
        if (timeBuilder_ == null) {
          return time_ == null ? com.amazaar.Protobuff.TimePbOuterClass.TimePb.getDefaultInstance() : time_;
        } else {
          return timeBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.amazaar.Protobuff.TimePb time = 6;</code>
       */
      public Builder setTime(com.amazaar.Protobuff.TimePbOuterClass.TimePb value) {
        if (timeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          time_ = value;
          onChanged();
        } else {
          timeBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.amazaar.Protobuff.TimePb time = 6;</code>
       */
      public Builder setTime(
          com.amazaar.Protobuff.TimePbOuterClass.TimePb.Builder builderForValue) {
        if (timeBuilder_ == null) {
          time_ = builderForValue.build();
          onChanged();
        } else {
          timeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.amazaar.Protobuff.TimePb time = 6;</code>
       */
      public Builder mergeTime(com.amazaar.Protobuff.TimePbOuterClass.TimePb value) {
        if (timeBuilder_ == null) {
          if (time_ != null) {
            time_ =
              com.amazaar.Protobuff.TimePbOuterClass.TimePb.newBuilder(time_).mergeFrom(value).buildPartial();
          } else {
            time_ = value;
          }
          onChanged();
        } else {
          timeBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.amazaar.Protobuff.TimePb time = 6;</code>
       */
      public Builder clearTime() {
        if (timeBuilder_ == null) {
          time_ = null;
          onChanged();
        } else {
          time_ = null;
          timeBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.amazaar.Protobuff.TimePb time = 6;</code>
       */
      public com.amazaar.Protobuff.TimePbOuterClass.TimePb.Builder getTimeBuilder() {
        
        onChanged();
        return getTimeFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.amazaar.Protobuff.TimePb time = 6;</code>
       */
      public com.amazaar.Protobuff.TimePbOuterClass.TimePbOrBuilder getTimeOrBuilder() {
        if (timeBuilder_ != null) {
          return timeBuilder_.getMessageOrBuilder();
        } else {
          return time_ == null ?
              com.amazaar.Protobuff.TimePbOuterClass.TimePb.getDefaultInstance() : time_;
        }
      }
      /**
       * <code>.com.amazaar.Protobuff.TimePb time = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.amazaar.Protobuff.TimePbOuterClass.TimePb, com.amazaar.Protobuff.TimePbOuterClass.TimePb.Builder, com.amazaar.Protobuff.TimePbOuterClass.TimePbOrBuilder> 
          getTimeFieldBuilder() {
        if (timeBuilder_ == null) {
          timeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.amazaar.Protobuff.TimePbOuterClass.TimePb, com.amazaar.Protobuff.TimePbOuterClass.TimePb.Builder, com.amazaar.Protobuff.TimePbOuterClass.TimePbOrBuilder>(
                  getTime(),
                  getParentForChildren(),
                  isClean());
          time_ = null;
        }
        return timeBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.amazaar.Protobuff.PaymentPb)
    }

    // @@protoc_insertion_point(class_scope:com.amazaar.Protobuff.PaymentPb)
    private static final com.amazaar.Protobuff.PaymentPbOuterClass.PaymentPb DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.amazaar.Protobuff.PaymentPbOuterClass.PaymentPb();
    }

    public static com.amazaar.Protobuff.PaymentPbOuterClass.PaymentPb getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PaymentPb>
        PARSER = new com.google.protobuf.AbstractParser<PaymentPb>() {
      @java.lang.Override
      public PaymentPb parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PaymentPb(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PaymentPb> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PaymentPb> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.amazaar.Protobuff.PaymentPbOuterClass.PaymentPb getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_amazaar_Protobuff_PaymentPb_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_amazaar_Protobuff_PaymentPb_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017paymentPb.proto\022\025com.amazaar.Protobuff" +
      "\032\020customerPb.proto\032\014timePb.proto\"\342\001\n\tPay" +
      "mentPb\022\r\n\005txnId\030\001 \001(\t\022\024\n\014responseCode\030\002 " +
      "\001(\t\0228\n\006status\030\003 \001(\0162(.com.amazaar.Protob" +
      "uff.PaymentStatusEnum\022\016\n\006txnRef\030\004 \001(\t\0229\n" +
      "\013customerRef\030\005 \001(\0132$.com.amazaar.Protobu" +
      "ff.CustomerPbRef\022+\n\004time\030\006 \001(\0132\035.com.ama" +
      "zaar.Protobuff.TimePb*U\n\021PaymentStatusEn" +
      "um\022\032\n\026UNKNOWN_PAYMENT_STATUS\020\000\022\013\n\007SUCCES" +
      "S\020\001\022\n\n\006FAILED\020\002\022\013\n\007WAITING\020\003*I\n\017PaymentM" +
      "odeEnum\022\020\n\014UNKNOWN_MODE\020\000\022\016\n\nGOOGLE_PAY\020" +
      "\001\022\024\n\020CASH_ON_DELIVERY\020\002b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.amazaar.Protobuff.CustomerPbOuterClass.getDescriptor(),
          com.amazaar.Protobuff.TimePbOuterClass.getDescriptor(),
        });
    internal_static_com_amazaar_Protobuff_PaymentPb_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_amazaar_Protobuff_PaymentPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_amazaar_Protobuff_PaymentPb_descriptor,
        new java.lang.String[] { "TxnId", "ResponseCode", "Status", "TxnRef", "CustomerRef", "Time", });
    com.amazaar.Protobuff.CustomerPbOuterClass.getDescriptor();
    com.amazaar.Protobuff.TimePbOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
