// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: registrationPb.proto

package com.amazaar.Protobuff;

public final class RegistrationPbOuterClass {
  private RegistrationPbOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RegistrationPbOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.amazaar.Protobuff.RegistrationPb)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.amazaar.Protobuff.CustomerPb customer = 1;</code>
     * @return Whether the customer field is set.
     */
    boolean hasCustomer();
    /**
     * <code>.com.amazaar.Protobuff.CustomerPb customer = 1;</code>
     * @return The customer.
     */
    com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPb getCustomer();
    /**
     * <code>.com.amazaar.Protobuff.CustomerPb customer = 1;</code>
     */
    com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPbOrBuilder getCustomerOrBuilder();

    /**
     * <code>.com.amazaar.Protobuff.LoginPb login = 2;</code>
     * @return Whether the login field is set.
     */
    boolean hasLogin();
    /**
     * <code>.com.amazaar.Protobuff.LoginPb login = 2;</code>
     * @return The login.
     */
    com.amazaar.Protobuff.LoginPbOuterClass.LoginPb getLogin();
    /**
     * <code>.com.amazaar.Protobuff.LoginPb login = 2;</code>
     */
    com.amazaar.Protobuff.LoginPbOuterClass.LoginPbOrBuilder getLoginOrBuilder();
  }
  /**
   * Protobuf type {@code com.amazaar.Protobuff.RegistrationPb}
   */
  public static final class RegistrationPb extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.amazaar.Protobuff.RegistrationPb)
      RegistrationPbOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RegistrationPb.newBuilder() to construct.
    private RegistrationPb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RegistrationPb() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RegistrationPb();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RegistrationPb(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPb.Builder subBuilder = null;
              if (customer_ != null) {
                subBuilder = customer_.toBuilder();
              }
              customer_ = input.readMessage(com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPb.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(customer_);
                customer_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              com.amazaar.Protobuff.LoginPbOuterClass.LoginPb.Builder subBuilder = null;
              if (login_ != null) {
                subBuilder = login_.toBuilder();
              }
              login_ = input.readMessage(com.amazaar.Protobuff.LoginPbOuterClass.LoginPb.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(login_);
                login_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.amazaar.Protobuff.RegistrationPbOuterClass.internal_static_com_amazaar_Protobuff_RegistrationPb_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.amazaar.Protobuff.RegistrationPbOuterClass.internal_static_com_amazaar_Protobuff_RegistrationPb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.amazaar.Protobuff.RegistrationPbOuterClass.RegistrationPb.class, com.amazaar.Protobuff.RegistrationPbOuterClass.RegistrationPb.Builder.class);
    }

    public static final int CUSTOMER_FIELD_NUMBER = 1;
    private com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPb customer_;
    /**
     * <code>.com.amazaar.Protobuff.CustomerPb customer = 1;</code>
     * @return Whether the customer field is set.
     */
    @java.lang.Override
    public boolean hasCustomer() {
      return customer_ != null;
    }
    /**
     * <code>.com.amazaar.Protobuff.CustomerPb customer = 1;</code>
     * @return The customer.
     */
    @java.lang.Override
    public com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPb getCustomer() {
      return customer_ == null ? com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPb.getDefaultInstance() : customer_;
    }
    /**
     * <code>.com.amazaar.Protobuff.CustomerPb customer = 1;</code>
     */
    @java.lang.Override
    public com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPbOrBuilder getCustomerOrBuilder() {
      return getCustomer();
    }

    public static final int LOGIN_FIELD_NUMBER = 2;
    private com.amazaar.Protobuff.LoginPbOuterClass.LoginPb login_;
    /**
     * <code>.com.amazaar.Protobuff.LoginPb login = 2;</code>
     * @return Whether the login field is set.
     */
    @java.lang.Override
    public boolean hasLogin() {
      return login_ != null;
    }
    /**
     * <code>.com.amazaar.Protobuff.LoginPb login = 2;</code>
     * @return The login.
     */
    @java.lang.Override
    public com.amazaar.Protobuff.LoginPbOuterClass.LoginPb getLogin() {
      return login_ == null ? com.amazaar.Protobuff.LoginPbOuterClass.LoginPb.getDefaultInstance() : login_;
    }
    /**
     * <code>.com.amazaar.Protobuff.LoginPb login = 2;</code>
     */
    @java.lang.Override
    public com.amazaar.Protobuff.LoginPbOuterClass.LoginPbOrBuilder getLoginOrBuilder() {
      return getLogin();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (customer_ != null) {
        output.writeMessage(1, getCustomer());
      }
      if (login_ != null) {
        output.writeMessage(2, getLogin());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (customer_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getCustomer());
      }
      if (login_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getLogin());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.amazaar.Protobuff.RegistrationPbOuterClass.RegistrationPb)) {
        return super.equals(obj);
      }
      com.amazaar.Protobuff.RegistrationPbOuterClass.RegistrationPb other = (com.amazaar.Protobuff.RegistrationPbOuterClass.RegistrationPb) obj;

      if (hasCustomer() != other.hasCustomer()) return false;
      if (hasCustomer()) {
        if (!getCustomer()
            .equals(other.getCustomer())) return false;
      }
      if (hasLogin() != other.hasLogin()) return false;
      if (hasLogin()) {
        if (!getLogin()
            .equals(other.getLogin())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCustomer()) {
        hash = (37 * hash) + CUSTOMER_FIELD_NUMBER;
        hash = (53 * hash) + getCustomer().hashCode();
      }
      if (hasLogin()) {
        hash = (37 * hash) + LOGIN_FIELD_NUMBER;
        hash = (53 * hash) + getLogin().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.amazaar.Protobuff.RegistrationPbOuterClass.RegistrationPb parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.amazaar.Protobuff.RegistrationPbOuterClass.RegistrationPb parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.amazaar.Protobuff.RegistrationPbOuterClass.RegistrationPb parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.amazaar.Protobuff.RegistrationPbOuterClass.RegistrationPb parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.amazaar.Protobuff.RegistrationPbOuterClass.RegistrationPb parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.amazaar.Protobuff.RegistrationPbOuterClass.RegistrationPb parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.amazaar.Protobuff.RegistrationPbOuterClass.RegistrationPb parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.amazaar.Protobuff.RegistrationPbOuterClass.RegistrationPb parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.amazaar.Protobuff.RegistrationPbOuterClass.RegistrationPb parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.amazaar.Protobuff.RegistrationPbOuterClass.RegistrationPb parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.amazaar.Protobuff.RegistrationPbOuterClass.RegistrationPb parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.amazaar.Protobuff.RegistrationPbOuterClass.RegistrationPb parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.amazaar.Protobuff.RegistrationPbOuterClass.RegistrationPb prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.amazaar.Protobuff.RegistrationPb}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.amazaar.Protobuff.RegistrationPb)
        com.amazaar.Protobuff.RegistrationPbOuterClass.RegistrationPbOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.amazaar.Protobuff.RegistrationPbOuterClass.internal_static_com_amazaar_Protobuff_RegistrationPb_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.amazaar.Protobuff.RegistrationPbOuterClass.internal_static_com_amazaar_Protobuff_RegistrationPb_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.amazaar.Protobuff.RegistrationPbOuterClass.RegistrationPb.class, com.amazaar.Protobuff.RegistrationPbOuterClass.RegistrationPb.Builder.class);
      }

      // Construct using com.amazaar.Protobuff.RegistrationPbOuterClass.RegistrationPb.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (customerBuilder_ == null) {
          customer_ = null;
        } else {
          customer_ = null;
          customerBuilder_ = null;
        }
        if (loginBuilder_ == null) {
          login_ = null;
        } else {
          login_ = null;
          loginBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.amazaar.Protobuff.RegistrationPbOuterClass.internal_static_com_amazaar_Protobuff_RegistrationPb_descriptor;
      }

      @java.lang.Override
      public com.amazaar.Protobuff.RegistrationPbOuterClass.RegistrationPb getDefaultInstanceForType() {
        return com.amazaar.Protobuff.RegistrationPbOuterClass.RegistrationPb.getDefaultInstance();
      }

      @java.lang.Override
      public com.amazaar.Protobuff.RegistrationPbOuterClass.RegistrationPb build() {
        com.amazaar.Protobuff.RegistrationPbOuterClass.RegistrationPb result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.amazaar.Protobuff.RegistrationPbOuterClass.RegistrationPb buildPartial() {
        com.amazaar.Protobuff.RegistrationPbOuterClass.RegistrationPb result = new com.amazaar.Protobuff.RegistrationPbOuterClass.RegistrationPb(this);
        if (customerBuilder_ == null) {
          result.customer_ = customer_;
        } else {
          result.customer_ = customerBuilder_.build();
        }
        if (loginBuilder_ == null) {
          result.login_ = login_;
        } else {
          result.login_ = loginBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.amazaar.Protobuff.RegistrationPbOuterClass.RegistrationPb) {
          return mergeFrom((com.amazaar.Protobuff.RegistrationPbOuterClass.RegistrationPb)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.amazaar.Protobuff.RegistrationPbOuterClass.RegistrationPb other) {
        if (other == com.amazaar.Protobuff.RegistrationPbOuterClass.RegistrationPb.getDefaultInstance()) return this;
        if (other.hasCustomer()) {
          mergeCustomer(other.getCustomer());
        }
        if (other.hasLogin()) {
          mergeLogin(other.getLogin());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.amazaar.Protobuff.RegistrationPbOuterClass.RegistrationPb parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.amazaar.Protobuff.RegistrationPbOuterClass.RegistrationPb) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPb customer_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPb, com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPb.Builder, com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPbOrBuilder> customerBuilder_;
      /**
       * <code>.com.amazaar.Protobuff.CustomerPb customer = 1;</code>
       * @return Whether the customer field is set.
       */
      public boolean hasCustomer() {
        return customerBuilder_ != null || customer_ != null;
      }
      /**
       * <code>.com.amazaar.Protobuff.CustomerPb customer = 1;</code>
       * @return The customer.
       */
      public com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPb getCustomer() {
        if (customerBuilder_ == null) {
          return customer_ == null ? com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPb.getDefaultInstance() : customer_;
        } else {
          return customerBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.amazaar.Protobuff.CustomerPb customer = 1;</code>
       */
      public Builder setCustomer(com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPb value) {
        if (customerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          customer_ = value;
          onChanged();
        } else {
          customerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.amazaar.Protobuff.CustomerPb customer = 1;</code>
       */
      public Builder setCustomer(
          com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPb.Builder builderForValue) {
        if (customerBuilder_ == null) {
          customer_ = builderForValue.build();
          onChanged();
        } else {
          customerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.amazaar.Protobuff.CustomerPb customer = 1;</code>
       */
      public Builder mergeCustomer(com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPb value) {
        if (customerBuilder_ == null) {
          if (customer_ != null) {
            customer_ =
              com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPb.newBuilder(customer_).mergeFrom(value).buildPartial();
          } else {
            customer_ = value;
          }
          onChanged();
        } else {
          customerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.amazaar.Protobuff.CustomerPb customer = 1;</code>
       */
      public Builder clearCustomer() {
        if (customerBuilder_ == null) {
          customer_ = null;
          onChanged();
        } else {
          customer_ = null;
          customerBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.amazaar.Protobuff.CustomerPb customer = 1;</code>
       */
      public com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPb.Builder getCustomerBuilder() {
        
        onChanged();
        return getCustomerFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.amazaar.Protobuff.CustomerPb customer = 1;</code>
       */
      public com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPbOrBuilder getCustomerOrBuilder() {
        if (customerBuilder_ != null) {
          return customerBuilder_.getMessageOrBuilder();
        } else {
          return customer_ == null ?
              com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPb.getDefaultInstance() : customer_;
        }
      }
      /**
       * <code>.com.amazaar.Protobuff.CustomerPb customer = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPb, com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPb.Builder, com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPbOrBuilder> 
          getCustomerFieldBuilder() {
        if (customerBuilder_ == null) {
          customerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPb, com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPb.Builder, com.amazaar.Protobuff.CustomerPbOuterClass.CustomerPbOrBuilder>(
                  getCustomer(),
                  getParentForChildren(),
                  isClean());
          customer_ = null;
        }
        return customerBuilder_;
      }

      private com.amazaar.Protobuff.LoginPbOuterClass.LoginPb login_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.amazaar.Protobuff.LoginPbOuterClass.LoginPb, com.amazaar.Protobuff.LoginPbOuterClass.LoginPb.Builder, com.amazaar.Protobuff.LoginPbOuterClass.LoginPbOrBuilder> loginBuilder_;
      /**
       * <code>.com.amazaar.Protobuff.LoginPb login = 2;</code>
       * @return Whether the login field is set.
       */
      public boolean hasLogin() {
        return loginBuilder_ != null || login_ != null;
      }
      /**
       * <code>.com.amazaar.Protobuff.LoginPb login = 2;</code>
       * @return The login.
       */
      public com.amazaar.Protobuff.LoginPbOuterClass.LoginPb getLogin() {
        if (loginBuilder_ == null) {
          return login_ == null ? com.amazaar.Protobuff.LoginPbOuterClass.LoginPb.getDefaultInstance() : login_;
        } else {
          return loginBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.amazaar.Protobuff.LoginPb login = 2;</code>
       */
      public Builder setLogin(com.amazaar.Protobuff.LoginPbOuterClass.LoginPb value) {
        if (loginBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          login_ = value;
          onChanged();
        } else {
          loginBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.amazaar.Protobuff.LoginPb login = 2;</code>
       */
      public Builder setLogin(
          com.amazaar.Protobuff.LoginPbOuterClass.LoginPb.Builder builderForValue) {
        if (loginBuilder_ == null) {
          login_ = builderForValue.build();
          onChanged();
        } else {
          loginBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.amazaar.Protobuff.LoginPb login = 2;</code>
       */
      public Builder mergeLogin(com.amazaar.Protobuff.LoginPbOuterClass.LoginPb value) {
        if (loginBuilder_ == null) {
          if (login_ != null) {
            login_ =
              com.amazaar.Protobuff.LoginPbOuterClass.LoginPb.newBuilder(login_).mergeFrom(value).buildPartial();
          } else {
            login_ = value;
          }
          onChanged();
        } else {
          loginBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.amazaar.Protobuff.LoginPb login = 2;</code>
       */
      public Builder clearLogin() {
        if (loginBuilder_ == null) {
          login_ = null;
          onChanged();
        } else {
          login_ = null;
          loginBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.amazaar.Protobuff.LoginPb login = 2;</code>
       */
      public com.amazaar.Protobuff.LoginPbOuterClass.LoginPb.Builder getLoginBuilder() {
        
        onChanged();
        return getLoginFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.amazaar.Protobuff.LoginPb login = 2;</code>
       */
      public com.amazaar.Protobuff.LoginPbOuterClass.LoginPbOrBuilder getLoginOrBuilder() {
        if (loginBuilder_ != null) {
          return loginBuilder_.getMessageOrBuilder();
        } else {
          return login_ == null ?
              com.amazaar.Protobuff.LoginPbOuterClass.LoginPb.getDefaultInstance() : login_;
        }
      }
      /**
       * <code>.com.amazaar.Protobuff.LoginPb login = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.amazaar.Protobuff.LoginPbOuterClass.LoginPb, com.amazaar.Protobuff.LoginPbOuterClass.LoginPb.Builder, com.amazaar.Protobuff.LoginPbOuterClass.LoginPbOrBuilder> 
          getLoginFieldBuilder() {
        if (loginBuilder_ == null) {
          loginBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.amazaar.Protobuff.LoginPbOuterClass.LoginPb, com.amazaar.Protobuff.LoginPbOuterClass.LoginPb.Builder, com.amazaar.Protobuff.LoginPbOuterClass.LoginPbOrBuilder>(
                  getLogin(),
                  getParentForChildren(),
                  isClean());
          login_ = null;
        }
        return loginBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.amazaar.Protobuff.RegistrationPb)
    }

    // @@protoc_insertion_point(class_scope:com.amazaar.Protobuff.RegistrationPb)
    private static final com.amazaar.Protobuff.RegistrationPbOuterClass.RegistrationPb DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.amazaar.Protobuff.RegistrationPbOuterClass.RegistrationPb();
    }

    public static com.amazaar.Protobuff.RegistrationPbOuterClass.RegistrationPb getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RegistrationPb>
        PARSER = new com.google.protobuf.AbstractParser<RegistrationPb>() {
      @java.lang.Override
      public RegistrationPb parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RegistrationPb(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RegistrationPb> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RegistrationPb> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.amazaar.Protobuff.RegistrationPbOuterClass.RegistrationPb getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_amazaar_Protobuff_RegistrationPb_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_amazaar_Protobuff_RegistrationPb_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024registrationPb.proto\022\025com.amazaar.Prot" +
      "obuff\032\020customerPb.proto\032\rloginPb.proto\"t" +
      "\n\016RegistrationPb\0223\n\010customer\030\001 \001(\0132!.com" +
      ".amazaar.Protobuff.CustomerPb\022-\n\005login\030\002" +
      " \001(\0132\036.com.amazaar.Protobuff.LoginPbb\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.amazaar.Protobuff.CustomerPbOuterClass.getDescriptor(),
          com.amazaar.Protobuff.LoginPbOuterClass.getDescriptor(),
        });
    internal_static_com_amazaar_Protobuff_RegistrationPb_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_amazaar_Protobuff_RegistrationPb_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_amazaar_Protobuff_RegistrationPb_descriptor,
        new java.lang.String[] { "Customer", "Login", });
    com.amazaar.Protobuff.CustomerPbOuterClass.getDescriptor();
    com.amazaar.Protobuff.LoginPbOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
